### PR TITLE
Remove well-alignedness assumption from pointer-into-array

### LINKED ISSUE #7265: Incorrect result when analyzing misaligned pointers
Running CBMC on the following program:

```
#include <assert.h>
#include <stdint.h>

int main() {
  uint16_t x[200];
  x[0] = 1;
  x[1] = 2;
  uint8_t* y = (uint8_t *)x;
  uint16_t z = *((uint16_t*)(y + 1));

  assert(z == 512u);
}
```

We get a `VERIFICATION FAILURE` result instead of success.

The program should be correct as assigning `y + 1` to `z` makes `z` to point to at the most significant byte of `x[0]` followed by the least significant byte of `x[1]`.

By looking at the trace it seems that the issue is caused by the removal of the alias `y` and then the `y + 1` operation, so  that `z = x[0]`, and this causes the verification failure.

Note that the problem happens even disabling all the simplification/constant propagation.

CBMC version: 5.66.0
Operating system: Mac OS
Exact command line resulting in the issue: `ncbmc --no-simplify --no-propagation --no-array-field-sensitivity byte-extract-complex.c
`
What behaviour did you expect: `VERIFICATION SUCCESS`
What happened instead: `VERIFICATION FAILURE`

### PR DESCRIPTION
**Pull request by tautschnig**
84df81e5 fixed the case for unaligned access into arrays when the dereference type did not match the size of array elements. This was, however, missing the case that an unaligned access into an array is done with matching dereference type size.

Co-authored-by: Enrico Steffinlongo <enrico.steffinlongo@diffblue.com>

Fixes: #7265

Please review commit-by-commit.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: regression/cbmc/Pointer_array7/main.c [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#include <assert.h>
+#include <stdint.h>
+
+int main()
+{
+  uint16_t x[2];
+  x[0] = 1;
+  x[1] = 2;
+  uint8_t *y = (uint8_t *)x;
+  uint16_t z = *((uint16_t *)(y + 1));
```
Comment (peterschrammel) [inline regression/cbmc/Pointer_array7/main.c:22]: ❓ Is `*((uint16_t *)(y + 3))` correctly detected as out-of-bounds?

File: regression/cbmc/Pointer_array7/test.desc [hunk 2]
```diff
@@ -0,0 +1,8 @@
+CORE
+main.c
+--little-endian
```
Comment (peterschrammel) [inline regression/cbmc/Pointer_array7/test.desc]: ❓ Do we also need a big-endian test?

File: src/pointer-analysis/value_set_dereference.cpp [hunk 3]
```diff
@@ -477,24 +477,28 @@ value_set_dereferencet::valuet value_set_dereferencet::build_reference_to(
...
-    else
-      return valuet{};
+    if(!o.offset().is_zero())
+      return {};
+
+    valuet result;
+    result.pointer = null_pointer_exprt{pointer_type};
+    return result;
   }
   else if(root_object.id()==ID_dynamic_object)
```
Comment (peterschrammel) [inline src/pointer-analysis/value_set_dereference.cpp:490]: ❓ ⛏️ Can the `else`s be removed now?

File: src/pointer-analysis/value_set_dereference.cpp [hunk 4]
```diff
@@ -612,16 +612,12 @@ value_set_dereferencet::valuet value_set_dereferencet::build_reference_to(
...
-          to_array_type(root_object_type).element_type().pretty();
-      }
-
       const auto offset_int =
         numeric_cast_v<mp_integer>(to_constant_expr(offset));
 
-      if(offset_int % *element_size == 0)
+      if(
+        element_size.has_value() && *element_size > 0 &&
+        offset_int % *element_size == 0)
```
Comment (peterschrammel) [inline src/pointer-analysis/value_set_dereference.cpp]: ❓ Have we got a test for this?

**Review by peterschrammel — APPROVED** [review]

File: regression/cbmc/Pointer_array7/main.c (hunk 1 above)
Comment (tautschnig) [reply regression/cbmc/Pointer_array7/main.c:22]: Yes, just confirmed that it is. (But also I think this isn't affected by this PR, so I'm not adding a test right here.)

File: regression/cbmc/Pointer_array7/test.desc (hunk 2 above)
Comment (tautschnig) [reply regression/cbmc/Pointer_array7/test.desc]: Added the big-endian variant.

File: src/pointer-analysis/value_set_dereference.cpp (hunk 3 above)
Comment (tautschnig) [reply src/pointer-analysis/value_set_dereference.cpp:490]: We could do this, I don't know whether it's worth the code churn? Let me know.

Comment (peterschrammel) [reply src/pointer-analysis/value_set_dereference.cpp:490]: Probably not, thus marked ⛏️

File: src/pointer-analysis/value_set_dereference.cpp (hunk 4 above)
Comment (tautschnig) [reply src/pointer-analysis/value_set_dereference.cpp]: I tried to craft one and failed to meet these conditions. I'll instead change these to invariants.
