### PR TITLE
Fix pointer havocing within loop invariant contracts

### LINKED ISSUE #5960: Loop invariant contract havocs a pointer instead of havocing its value
**CBMC version:** `develop`

**Operating system:** Mac OS 10.15.7

**Test case:**

```c
#include <assert.h>

void main()
{
  char *data = malloc(1);
  *data = 42;

  unsigned i;
  while(i > 0)
    __CPROVER_loop_invariant(*data == 42)
    {
      *data = 42;
      i--;
    }

  assert(*data = 42);
}
```

**Exact command line resulting in the issue:**

```
goto-cc -o test.gb test.c
goto-instrument --enforce-all-contracts test.gb test-loop.gb
cbmc --pointer-check test-loop.gb
```

**What behaviour did you expect:**

CBMC should be able to verify the goto program with the loop contracts properly enforced.

**What happened instead:**

CBMC complains that `data` is assigned to `NULL` and thus `*data = 42` may be invalid.

This happens because the `__CPROVER_loop_invariant` contract incorrectly havocs the write set of the loop -- instead of havocing `*data`, it havocs `data` and non-deterministically sets it to `NULL`.

### PR DESCRIPTION
**Pull request by SaswatPadhi**
Fixes #5960.

Please see the linked bug report for more information.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] NA ~~Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.~~
- [ ] NA ~~The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/~~
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] NA ~~My commit message includes data points confirming performance improvements (if claimed).~~
- [x] My PR is restricted to a single feature or bugfix.
- [ ] NA ~~White-space or formatting changes outside the feature-related changed lines are in commits of their own.~~

### CODE REVIEW

File: regression/contracts/invar_check_pointer_modifies/main.c [hunk 1]
```diff
@@ -0,0 +1,17 @@
+#include <assert.h>
```
Comment (feliperodri) [inline regression/contracts/invar_check_pointer_modifies/main.c]:
```c
#include <stdlib.h>
```
because of malloc.

File: regression/contracts/invar_check_pointer_modifies/test.desc [hunk 2]
```diff
@@ -0,0 +1,14 @@
+CORE
+main.c
+--enforce-all-contracts --pointer-check
+^EXIT=0$
+^SIGNAL=0$
+^\[main.1\] .* Check loop invariant before entry: SUCCESS$
+^\[main.2\] .* Check that loop invariant is preserved: SUCCESS$
+^\[main.assertion.1\] .* assertion r == 0: SUCCESS$
+^VERIFICATION SUCCESSFUL$
```
Comment (feliperodri) [inline regression/contracts/invar_check_pointer_modifies/test.desc]: Can we also add a negative test?

File: src/goto-instrument/loop_utils.cpp [hunk 3]
```diff
@@ -65,10 +65,9 @@ void get_modifies_lhs(
     modifies.insert(lhs);
   else if(lhs.id()==ID_dereference)
   {
-    modifiest m=local_may_alias.get(t, to_dereference_expr(lhs).pointer());
-    for(modifiest::const_iterator m_it=m.begin();
-        m_it!=m.end(); m_it++)
-      get_modifies_lhs(local_may_alias, t, *m_it, modifies);
+    auto pointer = to_dereference_expr(lhs).pointer();
```
Comment (feliperodri) [inline src/goto-instrument/loop_utils.cpp:68]: `address_of_exprt`?

**Review by feliperodri — CHANGES_REQUESTED** [review]

File: regression/contracts/invar_check_pointer_modifies/main.c (hunk 1 above)
Comment (SaswatPadhi) [reply regression/contracts/invar_check_pointer_modifies/main.c]: Thanks. Done.

File: regression/contracts/invar_check_pointer_modifies/test.desc (hunk 2 above)
Comment (SaswatPadhi) [reply regression/contracts/invar_check_pointer_modifies/test.desc]: Good idea! Added one for aliased pointers :)

File: regression/contracts/invar_check_pointer_modifies-01/main.c [hunk 4]
```diff
@@ -0,0 +1,18 @@
+#include <assert.h>
+#include <stdlib.h>
+
```
Comment (tautschnig) [inline regression/contracts/invar_check_pointer_modifies-01/main.c:3]: Random location for comment: would you mind merging the second commit (the regression test) into the first one? When later looking at git history, this makes it much easier to understand why a particular change was made.

File: src/goto-instrument/loop_utils.cpp (hunk 3 above)
Comment (tautschnig) [inline src/goto-instrument/loop_utils.cpp]: `const auto &pointer` (or perhaps `const exprt &pointer`)

**Review by feliperodri — APPROVED** [review]
LGTM.

File: src/goto-instrument/loop_utils.cpp [hunk 5]
```diff
@@ -65,10 +65,9 @@ void get_modifies_lhs(
...
+    for(const auto &mod : local_may_alias.get(t, pointer))
+      modifies.insert(dereference_exprt{mod, mod.type().subtype()});
```
Comment (tautschnig) [inline src/goto-instrument/loop_utils.cpp]: `dereference_exprt{mod}` should work, I believe.

**Review by tautschnig — APPROVED** [review]

File: regression/contracts/invar_check_pointer_modifies-01/main.c (hunk 4 above)
Comment (SaswatPadhi) [reply regression/contracts/invar_check_pointer_modifies-01/main.c:3]: Makes sense, thanks for the quick feedback!

File: src/goto-instrument/loop_utils.cpp (hunk 3 above)
Comment (SaswatPadhi) [reply src/goto-instrument/loop_utils.cpp]: Thanks. Done.

File: src/goto-instrument/loop_utils.cpp (hunk 5 above)
Comment (SaswatPadhi) [reply src/goto-instrument/loop_utils.cpp]: Thanks. Done.

**Review by peterschrammel — APPROVED** [review]
