### PR TITLE
CONTRACTS: Fix conditional havoc code

### LINKED ISSUE #7379: Bug in contract replacement with conditional assings clauses
CBMC version: 5.69.1 (cbmc-5.59.0-676-gb4a4122dee)
Operating system: N/A
Exact command line resulting in the issue:
```
goto-cc main.c -o main.goto
goto-instrument --dfcc main --enforce-contract bar --replace-call-with-contract foo main.goto main-mod.goto
cbmc main-mod.goto --pointer-check
```
What behaviour did you expect: No failures.
What happened instead: NULL pointer derefecences.

```c
#include<stdlib.h>

void foo(int *out)
__CPROVER_requires(out == NULL || __CPROVER_is_fresh(out, sizeof(*out)))
__CPROVER_assigns(out != NULL : *out)
{
    if(out)
        *out = 1;
}

void bar()
{
    foo(NULL);
}

int main(void)
{
    bar();
}
```

### PR DESCRIPTION
**Pull request by remi-delmas-3000**
Fixes #7379 

The condition was being checked on the write set variable instead of write set element variable

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: regression/contracts-dfcc/havoc-conditional-target/check-foo.c [hunk 1]
```diff
@@ -0,0 +1,21 @@
+#include <assert.h>
```
Comment (feliperodri) [inline regression/contracts-dfcc/havoc-conditional-target/check-foo.c]: We don't need this include.

File: regression/contracts-dfcc/havoc-conditional-target/check-foo.desc [hunk 2]
```diff
@@ -0,0 +1,9 @@
+CORE
+check-foo.c
+--dfcc main --enforce-contract foo _ --pointer-check
+^EXIT=0$
+^SIGNAL=0$
+^VERIFICATION SUCCESSFUL$
+--
+--
+This test checks conditional havocs are behaving as expected.
```
Comment (feliperodri) [inline regression/contracts-dfcc/havoc-conditional-target/check-foo.desc]: Add newline.

File: regression/contracts-dfcc/havoc-conditional-target/replace-foo.c [hunk 3]
```diff
@@ -0,0 +1,31 @@
+#include <assert.h>
```
Comment (feliperodri) [inline regression/contracts-dfcc/havoc-conditional-target/replace-foo.c]: We don't need this include.

File: regression/contracts-dfcc/havoc-conditional-target/replace-foo.desc [hunk 4]
```diff
@@ -0,0 +1,9 @@
+CORE
+replace-foo.c
+--dfcc main --enforce-contract bar --replace-call-with-contract foo _ --pointer-check
+^EXIT=0$
+^SIGNAL=0$
+^VERIFICATION SUCCESSFUL$
+--
+--
+This test checks conditional havocs are behaving as expected.
```
Comment (feliperodri) [inline regression/contracts-dfcc/havoc-conditional-target/replace-foo.desc]: Add newline.

**Review by feliperodri — APPROVED** [review]
LGTM modulo a few clean ups.

File: src/ansi-c/library/cprover_contracts.c [hunk 5]
```diff
@@ -1286,6 +1286,10 @@ void *__CPROVER_contracts_write_set_havoc_get_assignable_target(
   __CPROVER_size_t idx)
 {
 __CPROVER_HIDE:;
+#ifdef DFCC_DEBUG
```
Comment (tautschnig) [inline src/ansi-c/library/cprover_contracts.c:1289]: How to set this/when is this set?

File: src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp [hunk 6]
```diff
@@ -233,7 +232,8 @@ void dfcc_spec_functionst::generate_havoc_function(
         body.add(goto_programt::make_function_call(call, location));
 
         auto goto_instruction = body.add(goto_programt::make_incomplete_goto(
-          utils.make_null_check_expr(write_set_var)));
+          utils.make_null_check_expr(target_expr)));
```
Comment (tautschnig) [inline src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp]: While at it: can a source location be added here (as second parameter to `make_incomplete_goto`)?

**Review by tautschnig — APPROVED** [review]

File: src/ansi-c/library/cprover_contracts.c (hunk 5 above)
Comment (remi-delmas-3000) [reply src/ansi-c/library/cprover_contracts.c:1289]: these debug macros should be set at build time but there's no direct way to do that yet.

File: src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp (hunk 6 above)
Comment (remi-delmas-3000) [reply src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp]: fixed

File: regression/contracts-dfcc/havoc-conditional-target/replace-foo.desc (hunk 4 above)
Comment (remi-delmas-3000) [reply regression/contracts-dfcc/havoc-conditional-target/replace-foo.desc]: fixed

File: regression/contracts-dfcc/havoc-conditional-target/replace-foo.c (hunk 3 above)
Comment (remi-delmas-3000) [reply regression/contracts-dfcc/havoc-conditional-target/replace-foo.c]: fixed

File: regression/contracts-dfcc/havoc-conditional-target/check-foo.desc (hunk 2 above)
Comment (remi-delmas-3000) [reply regression/contracts-dfcc/havoc-conditional-target/check-foo.desc]: fixed

File: regression/contracts-dfcc/havoc-conditional-target/check-foo.c (hunk 1 above)
Comment (remi-delmas-3000) [reply regression/contracts-dfcc/havoc-conditional-target/check-foo.c]: fixed
