### PR TITLE
Wrap return value in std::move (Clang 7 build fix)

### LINKED ISSUE #3238: Build fails with Clang 7.0 due to local variable copies
When building with Clang 7.0, I'm getting thousands of errors like this.
```
cbmc/src/pointer-analysis/value_set_fivr.cpp:360:10: error: local variable 'od' will be copied despite being returned by name [-Werror,-Wreturn-std-move]
  return od;
         ^~
/home/kareem/doc/cbmc/src/pointer-analysis/value_set_fivr.cpp:360:10: note: call 'std::move' explicitly to avoid copying
  return od;
         ^~
         std::move(od)
```
I'll fix these soon. Here's the environment:
```
> clang --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### PR DESCRIPTION
**Pull request by karkhaz**
This fixes #3238 (again).

### CODE REVIEW

**Review by tautschnig — APPROVED** [review]

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp [hunk 1]
```diff
@@ -1251,14 +1251,14 @@ exprt java_string_library_preprocesst::get_primitive_value_of_object(
         typecast_exprt(object, pointer_type), pointer_type.subtype());
       member_exprt deref_value(deref, value_comp.get_name(), value_comp.type());
       code.add(code_assignt(value, deref_value), loc);
-      return value;
+      return std::move(value);
```
Comment (thk123) [inline jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: What a bore. I thought RVO meant you didn't need to move locals on return...

**Review by thk123 — APPROVED** [review]
If it is required to compile, then it is required, but it makes me sad and I don't really understand why.

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp (hunk 1 above)
Comment (kroening) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: Yes, I am also bugged by this. The rule isn't hard ('the type must match'), but it's still super annoying.

Comment (tautschnig) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: See https://github.com/diffblue/cbmc/pull/3267#discussion_r230666420

Comment (thk123) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: Fair - so in this case could be fixed by changing return to `symbol_exprt`? This seems like the better fix since the docs explicitly says returns a symbol

Comment (tautschnig) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: Except ... it doesn't - there is a branch that returns a `nil_exprt`.

Comment (smowton) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: And presumably if you did `return optionalt<symbol_exprt>(...)` then that would need to be `std::move`'d as well?

Comment (tautschnig) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: I don't actually think so, it would likely be the best approach. Well, even if the `std::move` were required, it would still be cleaner.

**Comment by karkhaz** [comment]
@thk123 it's not "required to compile," it's actually a warning that can be disabled with `-Wno-return-std-move`---sorry that I didn't actually elaborate on this. If it's annoying then I suppose that we can change CMake to pass that flag to Clang? But I would vote against that, personally, it generally seems like a useful warning to have around.

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp (hunk 1 above)
Comment (karkhaz) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: I'll try to use `optionalt` since I have a compiler to test with, I'll let you know how it goes in a few moments...

Comment (karkhaz) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: OK, please have a look at the updated patch. Indeed, `std::move` is not required. `get_primitive_value_of_object` now returns an `optionalt<symbol_exprt>`, and I've updated its only caller accordingly...please let me know if the call site looks wrong, I'm not sure that I did the right thing.

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp [hunk 2]
```diff
@@ -1222,7 +1222,7 @@ exprt java_string_library_preprocesst::get_primitive_value_of_object(
     object_type=symbol_typet("java::java.lang.Double");
   }
   else if(type_name==ID_void)
-    return nil_exprt();
+    return optionalt<symbol_exprt>();
```
Comment (tautschnig) [inline jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: I think we usually just use `return {};` in those cases.

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp [hunk 3]
```diff
@@ -1251,14 +1251,14 @@ exprt java_string_library_preprocesst::get_primitive_value_of_object(
         typecast_exprt(object, pointer_type), pointer_type.subtype());
       member_exprt deref_value(deref, value_comp.get_name(), value_comp.type());
       code.add(code_assignt(value, deref_value), loc);
-      return value;
+      return optionalt<symbol_exprt>(value);
```
Comment (tautschnig) [inline jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: Wouldn't `return value;` just work?

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp [hunk 4]
```diff
@@ -1398,9 +1399,12 @@ exprt java_string_library_preprocesst::make_argument_for_format(
     }
     else if(name==ID_int || name==ID_float || name==ID_char || name==ID_boolean)
     {
-      exprt value=get_primitive_value_of_object(
+      optionalt<symbol_exprt> value = get_primitive_value_of_object(
```
Comment (tautschnig) [inline jbmc/src/java_bytecode/java_string_library_preprocess.cpp]: It's probably ok to do `const auto value = ...`

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp [hunk 5]
```diff
@@ -1398,9 +1399,12 @@ exprt java_string_library_preprocesst::make_argument_for_format(
...
         arg_i, name, loc, symbol_table, code_not_null);
-      code_not_null.add(code_assignt(field_expr, value), loc);
+      if(value.has_value())
+        code_not_null.add(code_assignt(field_expr, *value), loc);
+      else
+        code_not_null.add(code_assignt(field_expr, nil_exprt()), loc);
```
Comment (tautschnig) [inline jbmc/src/java_bytecode/java_string_library_preprocess.cpp:1407]: Puh, I'm pretty sure this is broken and has actually been all along? @romainbrenguier maybe?

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 645dce0056b9a12f2f482e7d7353198b36aa4b06).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90853799
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Comment by karkhaz** [comment]
Do I need to rebase, or will the compatibility checks pick up my latest push automatically @allredj?

I resolved all of @tautschnig's suggestions except one.

**Comment by thk123** [comment]
Heh yeah I consider warnings as not compiling since we compile with warnings as errors!

**Comment by thk123** [comment]
@karkhaz I think you should leave it - Joels bot refers to an old commit id so I imagine the new one is still running.

**Review by allredj — COMMENTED** [review]
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 678b730638da9812cc559ad855f27f1a01428139).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90863299
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: d6e1984224186f88538c00fa25c7b9a9cf8ca235).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90866577

File: jbmc/src/java_bytecode/java_string_library_preprocess.cpp (hunk 5 above)
Comment (romainbrenguier) [reply jbmc/src/java_bytecode/java_string_library_preprocess.cpp:1407]: The else case should never happen, it would be better to put an invariant here.
The nil_exprt case happen for name == ID_void, which is excluded by the if condition.
