### PR TITLE
Do not generate enum-value checks for function call left-hand sides

### LINKED ISSUE #6586: __CPROVER_enum_is_in_range() fails on enum value returning functions.
CBMC version: 5.48.0 (cbmc-5.48.0)
Operating system: macOS 12.1 (21C52)
Exact command line resulting in the issue: cbmc --enum-range-check x.c
What behaviour did you expect: VERIFICATION SUCCESSFUL
What happened instead: VERIFICATION FAILED

This is the test code
```
// x.c

enum enm { first, second, third, fourth, };

static enum enm efunc(void)
{
    return second;
}

int main(void)
{
    enum enm e = efunc();
    __CPROVER_assert(__CPROVER_enum_is_in_range(e), "enum failure");
    return (e);
}
```

The verification result when verified with `cbmc --enum-range-check x.c` 
```
** Results:
x.c function main
[main.enum-range-check.1] line 12 enum range check in return_value_efunc: FAILURE
[main.enum-range-check.2] line 12 enum range check in return_value_efunc: SUCCESS
[main.assertion.1] line 13 enum failure: SUCCESS
[main.enum-range-check.3] line 13 enum range check in e: SUCCESS
[main.enum-range-check.4] line 13 enum range check in e: SUCCESS
[main.enum-range-check.5] line 13 enum range check in e: SUCCESS
[main.enum-range-check.6] line 13 enum range check in e: SUCCESS
[main.enum-range-check.7] line 14 enum range check in e: SUCCESS

** 1 of 8 failed (2 iterations)
VERIFICATION FAILED
```

The verification reports failure in line 12 `enum enm e = efunc();`. 
Replacing function call with e.g. `enum enm e = second;` will give successful verification, as expected.

### PR DESCRIPTION
**Pull request by tautschnig**
We already disabled these checks for assignment left-hand sides, but
need to do the same for function calls. Else we'd be asserting validity
before the value has been assigned.

Fixes: #6586

Co-authored-by: Ilia Levin <eli@literatecode.com>

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by TGWDB — APPROVED** [review]

File: regression/cbmc/enum_is_in_range/no_duplicate.c [hunk 1]
```diff
@@ -0,0 +1,19 @@
+enum enm
+{
+  first,
+  second,
+  third,
+  fourth,
```
Comment (danielsn) [inline regression/cbmc/enum_is_in_range/no_duplicate.c]: Consider testing non-contiguous  enums

Comment (tautschnig) [reply regression/cbmc/enum_is_in_range/no_duplicate.c]: Done.

**Review by chrisr-diffblue — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]
