### PR TITLE
Replace cout/cerr in solvers

### LINKED ISSUE #1757: Replace uses of cout and cerr
Directly printing to cout or cerr makes XML and JSON output unparseable. *ALL* output must be done through a message stream.
In particular in solver/flattening, lots of error messages are still printed to cout or cerr. They should be attached to the exception thrown.

More work needs to be done for:
src/cbmc/bmc.cpp
src/cbmc/cbmc_dimacs.cpp
src/cbmc/cbmc_parse_options.cpp
src/cbmc/cbmc_solvers.cpp
src/cbmc/show_vcc.cpp
src/cbmc/symex_coverage.cpp
src/cbmc/xml_interface.cpp
src/clobber/clobber_parse_options.cpp
src/goto-analyzer/goto_analyzer_parse_options.cpp
src/goto-analyzer/taint_analysis.cpp
src/goto-cc/as_mode.cpp
src/goto-cc/compile.cpp
src/goto-cc/cw_mode.cpp
src/goto-cc/gcc_mode.cpp
src/goto-cc/goto_cc_mode.cpp-#include "goto_cc_mode.h"
src/goto-cc/goto_cc_mode.cpp-
src/goto-cc/goto_cc_mode.cpp-#include <cstdio>
src/goto-cc/goto_cc_mode.cpp:#include <iostream>
src/goto-cc/linker_script_merge.cpp
src/goto-cc/ms_cl_mode.cpp
src/goto-diff/change_impact.cpp
src/goto-diff/goto_diff_parse_options.cpp
src/goto-instrument/accelerate/accelerate.cpp
src/goto-instrument/accelerate/acceleration_utils.cpp
src/goto-instrument/accelerate/all_paths_enumerator.cpp
src/goto-instrument/accelerate/cone_of_influence.cpp
src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
src/goto-instrument/accelerate/enumerating_loop_acceleration.cpp
src/goto-instrument/accelerate/overflow_instrumenter.cpp
src/goto-instrument/accelerate/path.cpp
src/goto-instrument/accelerate/polynomial_accelerator.cpp
src/goto-instrument/accelerate/sat_path_enumerator.cpp
src/goto-instrument/accelerate/trace_automaton.cpp
src/goto-instrument/accelerate/util.cpp
src/goto-instrument/call_sequences.cpp
src/goto-instrument/count_eloc.cpp
src/goto-instrument/dot.cpp
src/goto-instrument/goto_instrument_parse_options.cpp
src/goto-instrument/show_locations.cpp
src/goto-programs/goto_program_irep.cpp
src/goto-programs/loop_ids.cpp
src/goto-programs/show_symbol_table.cpp
src/goto-symex/slice_by_trace.cpp
src/jbmc/jbmc_parse_options.cpp
src/langapi/language_ui.cpp
src/memory-models/mmcc_parse_options.cpp
src/pointer-analysis/show_value_sets.cpp
src/solvers/miniBDD/miniBDD.cpp
src/solvers/sat/dimacs_cnf.cpp
src/util/irep_serialization.cpp
src/util/lispexpr.cpp
src/util/parse_options.cpp
src/util/xml_irep.cpp

### PR DESCRIPTION
**Pull request by peterschrammel**
Fixes 1757 partially

### CODE REVIEW

File: src/solvers/flattening/boolbv_equality.cpp [hunk 1]
```diff
@@ -21,9 +21,11 @@ literalt boolbvt::convert_equality(const equal_exprt &expr)
 {
   if(!base_type_eq(expr.lhs().type(), expr.rhs().type(), ns))
   {
-    std::cout << "######### lhs: " << expr.lhs().pretty() << '\n';
-    std::cout << "######### rhs: " << expr.rhs().pretty() << '\n';
-    throw "equality without matching types";
+    error().source_location=expr.find_source_location();
+    error() << "equality without matching types; \n"
```
Comment (tautschnig) [inline src/solvers/flattening/boolbv_equality.cpp]: 1. Replace `;` by `:`? No space before newline, please. (If anyone is pattern matching on those error messages they would easily get confused when trying to match on the full line.)
2. This entire check should be moved to `goto-symex` and should just be a `DATA_INVARIANT` using a plain equality test (no `base_type_eq`) here. This error does show up in some situations when pointer dereferencing messed up, but diagnosing it here is way too late as it provides poor customer experience and makes debugging impossible (the way to debug it is placing a check in goto-symex - been there, done that).

File: src/solvers/flattening/boolbv_equality.cpp [hunk 2]
```diff
@@ -70,9 +72,11 @@ literalt boolbvt::convert_verilog_case_equality(
 
   if(!base_type_eq(expr.lhs().type(), expr.rhs().type(), ns))
   {
-    std::cout << "######### lhs: " << expr.lhs().pretty() << '\n';
-    std::cout << "######### rhs: " << expr.rhs().pretty() << '\n';
-    throw "verilog_case_equality without matching types";
+    error().source_location=expr.find_source_location();
+    error() << "verilog_case_equality without matching types: \n"
```
Comment (tautschnig) [inline src/solvers/flattening/boolbv_equality.cpp]: No space before newline, please.

File: src/solvers/sat/cnf.cpp [hunk 3]
```diff
@@ -426,22 +427,23 @@ bool cnft::process_clause(const bvt &bv, bvt &dest)
...
       continue; // will remove later
 
-    if(l.var_no()>=_no_variables)
-      std::cout << "l.var_no()=" << l.var_no()
-                << " _no_variables=" << _no_variables << '\n';
-
-    assert(l.var_no()<_no_variables);
+    INVARIANT(
+      l.var_no() < _no_variables,
+      "unknown variable "+std::to_string(l.var_no())+" (no_variables = "+
```
Comment (tautschnig) [inline src/solvers/sat/cnf.cpp]: clang-format nit-pick: space around `+`

**Review by tautschnig — COMMENTED** [review]
I'm not sure the "Clang-format" commit is really necessary, but I accept that this particular file had a rather terrible formatting.

Could you please go one step further and check that all uses of `iostream` in solvers are either `#ifdef DEBUG`-guarded or strictly necessary for input/output?  I'd suggest to do `git grep -B1 iostream solvers/`.

**Comment by peterschrammel** [comment]
https://github.com/diffblue/cbmc/pull/1875#discussion-diff-170213904R25

Wouldn't this rather be a candidate for a `--validate` check, since examining every expression in symex could become quite costly? Or do you know the specific place where this problem usually occurs and a cheap DATA_INVARIANT could be put?

**Comment by tautschnig** [comment]
I think the main source of those errors is the result of `symex_assign`, and it would suffice to check consistency between lhs/rhs before `goto_symex_statet::assignment` returns. Indeed it might be a candidate for `--validate`, in line with yesterday's discussion of making `assert_l2_renaming` conditional on that. Hence: not to be implemented as part of this PR, but to be added to the virtual list of checks to be moved.

File: src/goto-symex/goto_symex_state.cpp [hunk 4]
```diff
@@ -288,8 +290,9 @@ static void assert_l1_renaming(const exprt &expr)
   #if 1
   if(check_renaming_l1(expr))
   {
-    std::cerr << expr.pretty() << '\n';
-    UNREACHABLE;
+    std::stringstream ss;
+    ss << "l1 renaming failed: \n" << expr.pretty();
+    DATA_INVARIANT(false, ss.str());
```
Comment (smowton) [inline src/goto-symex/goto_symex_state.cpp]: For simple things like this, std::string op+ is enough, no real need for sstream

File: src/solvers/flattening/boolbv_add_sub.cpp [hunk 5]
```diff
@@ -41,8 +39,10 @@ bvt boolbvt::convert_add_sub(const exprt &expr)
 
   if(op0.type()!=type)
   {
-    std::cerr << expr.pretty() << '\n';
-    throw "add/sub with mixed types";
+    error().source_location=expr.find_source_location();
+    error() << "add/sub with mixed types:\n"
+            << expr.pretty() << eom;
+    throw 0;
```
Comment (smowton) [inline src/solvers/flattening/boolbv_add_sub.cpp]: Reckon these are invariants not throws

**Review by smowton — COMMENTED** [review]
Does anybody catch the introduced `throw 0`s in a useful way? Should they just be invariants in most cases?

**Comment by tautschnig** [comment]
> Does anybody catch the introduced `throw 0`s in a useful way? Should they just be invariants in most cases?

Yes, the top-level *parse_options (i.e., the command-line front-ends) do and then print out the recorded `error` messages. Nevertheless I agree that those ought to be invariants. But that's to be a separate PR, I'd say.

**Comment by peterschrammel** [comment]
I leave the clean up of throws to https://github.com/diffblue/cbmc/issues/1314.

File: src/goto-symex/goto_symex_state.cpp [hunk 6]
```diff
@@ -51,11 +54,9 @@ void goto_symex_statet::level0t::operator()(
...
   const symbolt *s;
 
-  if(ns.lookup(obj_identifier, s))
-  {
-    std::cerr << "level0: failed to find " << obj_identifier << '\n';
-    abort();
-  }
+  bool found_level0 = !ns.lookup(obj_identifier, s);
+  INVARIANT(found_level0,
+            "level0: failed to find "+id2string(obj_identifier));
```
Comment (tautschnig) [inline src/goto-symex/goto_symex_state.cpp]: Nit pick: space around `+`

File: src/goto-symex/goto_symex_state.cpp [hunk 7]
```diff
@@ -288,8 +289,7 @@ static void assert_l1_renaming(const exprt &expr)
   #if 1
   if(check_renaming_l1(expr))
   {
-    std::cerr << expr.pretty() << '\n';
-    UNREACHABLE;
+    DATA_INVARIANT(false, "l1 renaming failed: \n" + expr.pretty());
```
Comment (tautschnig) [inline src/goto-symex/goto_symex_state.cpp]: Nit pick: no space after `:`

File: src/goto-symex/goto_symex_state.cpp [hunk 8]
```diff
@@ -301,8 +301,7 @@ static void assert_l2_renaming(const exprt &expr)
   #if 1
   if(check_renaming(expr))
   {
-    std::cerr << expr.pretty() << '\n';
-    UNREACHABLE;
+    DATA_INVARIANT(false, "l2 renaming failed: \n" + expr.pretty());
```
Comment (tautschnig) [inline src/goto-symex/goto_symex_state.cpp]: No space after `:`

**Review by tautschnig — APPROVED** [review]

File: src/solvers/sat/pbs_dimacs_cnf.cpp [hunk 9]
```diff
@@ -11,16 +11,23 @@ Author: Alex Groce
...
+  double d_sum = 0;
 
-  // std::cout << "enter: No Lit.=" << no_variables () << "\n";
+#ifdef DEBUG
+  std::cout << "enter: No Lit.=" << no_variables() << "\n";
+#endif
 
-  for(std::map<literalt, unsigned>::const_iterator it=pb_constraintmap.begin();
-      it!=pb_constraintmap.end(); ++it)
+  for(std::map<literalt, unsigned>::const_iterator it =
```
Comment (mgudemann) [inline src/solvers/sat/pbs_dimacs_cnf.cpp]: would it make sense to transform into ranged for en passant ?

**Review by mgudemann — APPROVED** [review]
LGTM

**Comment by tautschnig** [comment]
Would anyone be able to restart the AppVeyor build, unless @peterschrammel is going make further changes anyway?

AppVeyor said:
```
C:\projects\cbmc\src\goto-instrument\cover_instrument_mcdc.cpp : fatal error C1083: Cannot open compiler generated file: 'cover_instrument_mcdc.obj': Permission denied
```
This looks like a transient (and inexplicable) error to me.

**Comment by mgudemann** [comment]
@tauschnig I've come across that error before in some PR, very likely a
restart will solve this.

**Comment by chrisr-diffblue** [comment]
>
> This looks like a transient (and inexplicable) error to me.
>

I've seen similar on Windows builds at my previous job, and the two reasons
we came up with were (a) virus scanner running on the machine just happened
to have the file open in some state at the same time, and (b) there was
something about windows occasionally being slow to fully close/release all
file handles after a process had completed.

File: src/goto-symex/goto_symex_state.cpp [hunk 10]
```diff
@@ -51,11 +54,9 @@ void goto_symex_statet::level0t::operator()(
 
   const symbolt *s;
 
-  if(ns.lookup(obj_identifier, s))
-  {
-    std::cerr << "level0: failed to find " << obj_identifier << '\n';
-    abort();
-  }
```
Comment (martin-cs) [inline src/goto-symex/goto_symex_state.cpp:58]: We had abort() calls hidden in the depths of the system :-\  Scary...

File: src/analyses/invariant_set.cpp [hunk 11]
```diff
@@ -1134,7 +1137,9 @@ void invariant_sett::apply_code(const codet &code)
   }
   else
   {
-    std::cerr << code.pretty() << '\n';
-    throw "invariant_sett: unexpected statement: "+id2string(statement);
+    INVARIANT(
```
Comment (martin-cs) [inline src/analyses/invariant_set.cpp]: UNHANDLED_CASE seems more fitting than INVARIANT.  When we have some idea of what the program can contain during this analysis we may be able to say more.

File: src/goto-symex/goto_symex_state.cpp [hunk 12]
```diff
@@ -288,8 +289,7 @@ static void assert_l1_renaming(const exprt &expr)
   #if 1
   if(check_renaming_l1(expr))
   {
-    std::cerr << expr.pretty() << '\n';
-    UNREACHABLE;
+    DATA_INVARIANT(false, "l1 renaming failed:\n" + expr.pretty());
   }
```
Comment (martin-cs) [inline src/goto-symex/goto_symex_state.cpp]: I don't think this is a DATA_INVARIANT as it is not something that should always be true of an expr.  INVARIANT perhaps.

File: src/goto-symex/goto_symex_state.cpp [hunk 13]
```diff
@@ -301,8 +301,7 @@ static void assert_l2_renaming(const exprt &expr)
   #if 1
   if(check_renaming(expr))
   {
-    std::cerr << expr.pretty() << '\n';
-    UNREACHABLE;
+    DATA_INVARIANT(false, "l2 renaming failed:\n" + expr.pretty());
```
Comment (martin-cs) [inline src/goto-symex/goto_symex_state.cpp]: Ditto.

File: src/goto-symex/goto_symex_state.cpp [hunk 14]
```diff
@@ -288,8 +289,7 @@ static void assert_l1_renaming(const exprt &expr)
   #if 1
   if(check_renaming_l1(expr))
```
Comment (martin-cs) [inline src/goto-symex/goto_symex_state.cpp]: Is this side effect free?  If so, could we have INVARIANT(check_remaining_l1(expr), ...) ?  Maybe then we could also remove the #if 1?

File: src/solvers/flattening/boolbv_add_sub.cpp [hunk 15]
```diff
@@ -41,8 +39,9 @@ bvt boolbvt::convert_add_sub(const exprt &expr)
 
   if(op0.type()!=type)
   {
-    std::cerr << expr.pretty() << '\n';
-    throw "add/sub with mixed types";
+    error().source_location = expr.find_source_location();
+    error() << "add/sub with mixed types:\n" << expr.pretty() << eom;
+    throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_add_sub.cpp]: :-\  Please could we not increase the number of throw 0's.  This seems to me a pretty clear:

DATA_INVARIANT(op0.type()!=type, "add/sub arguments must have the same type")

File: src/solvers/flattening/boolbv_add_sub.cpp [hunk 16]
```diff
@@ -71,8 +70,9 @@ bvt boolbvt::convert_add_sub(const exprt &expr)
   {
     if(it->type()!=type)
     {
-      std::cerr << expr.pretty() << '\n';
-      throw "add/sub with mixed types";
+      error().source_location = expr.find_source_location();
+      error() << "add/sub with mixed types:\n" << expr.pretty() << eom;
+      throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_add_sub.cpp]: Ditto.

File: src/solvers/flattening/boolbv_case.cpp [hunk 17]
```diff
@@ -51,12 +49,12 @@ bvt boolbvt::convert_case(const exprt &expr)
...
-                  << it->pretty()
-                  << '\n';
-
-        throw "size of compare operand does not match";
+        error().source_location = expr.find_source_location();
+        error() << "size of compare operand does not match:\n"
+                << "compare operand: " << compare_bv.size()
+                << "\noperand: " << op.size() << '\n'
+                << it->pretty() << eom;
+        throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_case.cpp]: Again, looks like an INVARIANT of some kind to me.

File: src/solvers/flattening/boolbv_case.cpp [hunk 18]
```diff
@@ -70,12 +68,12 @@ bvt boolbvt::convert_case(const exprt &expr)
...
-                  << it->pretty()
-                  << '\n';
-
-        throw "size of value operand does not match";
+        error().source_location = expr.find_source_location();
+        error() << "size of value operand does not match:\n"
+                << "result size: " << bv.size() << "\noperand: " << op.size()
+                << '\n'
+                << it->pretty() << eom;
+        throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_case.cpp]: Ditto.

File: src/solvers/flattening/boolbv_cond.cpp [hunk 19]
```diff
@@ -53,12 +51,12 @@ bvt boolbvt::convert_cond(const exprt &expr)
...
-                    << it->pretty()
-                    << '\n';
-
-          throw "size of value operand does not match";
+          error().source_location = expr.find_source_location();
+          error() << "size of value operand does not match:\n"
+                  << "result size: " << bv.size() << "\noperand: " << op.size()
+                  << '\n'
+                  << it->pretty() << eom;
+          throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_cond.cpp]: Again.

File: src/solvers/flattening/boolbv_equality.cpp [hunk 20]
```diff
@@ -21,9 +19,11 @@ literalt boolbvt::convert_equality(const equal_exprt &expr)
...
   if(!base_type_eq(expr.lhs().type(), expr.rhs().type(), ns))
   {
-    std::cout << "######### lhs: " << expr.lhs().pretty() << '\n';
-    std::cout << "######### rhs: " << expr.rhs().pretty() << '\n';
-    throw "equality without matching types";
+    error().source_location = expr.find_source_location();
+    error() << "equality without matching types:\n"
+            << "######### lhs: " << expr.lhs().pretty() << '\n'
+            << "######### rhs: " << expr.rhs().pretty() << eom;
+    throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_equality.cpp]: DATA_INVARIANT.

File: src/solvers/flattening/boolbv_equality.cpp [hunk 21]
```diff
@@ -45,11 +45,13 @@ literalt boolbvt::convert_equality(const equal_exprt &expr)
...
-    std::cerr << "rhs: " << expr.rhs().pretty() << '\n';
-    std::cerr << "rhs size: " << bv1.size() << '\n';
-    throw "unexpected size mismatch on equality";
+    error().source_location = expr.find_source_location();
+    error() << "unexpected size mismatch on equality:\n"
+            << "lhs: " << expr.lhs().pretty() << '\n'
+            << "lhs size: " << bv0.size() << '\n'
+            << "rhs: " << expr.rhs().pretty() << '\n'
+            << "rhs size: " << bv1.size() << eom;
+    throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_equality.cpp]: CHECK_RETURN because this is an assumption about what convert_bv returns.

File: src/solvers/flattening/boolbv_equality.cpp [hunk 22]
```diff
@@ -70,21 +72,25 @@ literalt boolbvt::convert_verilog_case_equality(
...
   if(!base_type_eq(expr.lhs().type(), expr.rhs().type(), ns))
   {
-    std::cout << "######### lhs: " << expr.lhs().pretty() << '\n';
-    std::cout << "######### rhs: " << expr.rhs().pretty() << '\n';
-    throw "verilog_case_equality without matching types";
+    error().source_location = expr.find_source_location();
+    error() << "verilog_case_equality without matching types:\n"
+            << "######### lhs: " << expr.lhs().pretty() << '\n'
+            << "######### rhs: " << expr.rhs().pretty() << eom;
+    throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_equality.cpp]: DATA_INVARIANT.

File: src/solvers/flattening/boolbv_equality.cpp [hunk 23]
```diff
@@ -70,21 +72,25 @@ literalt boolbvt::convert_verilog_case_equality(
...
-    std::cerr << "rhs: " << expr.rhs().pretty() << '\n';
-    std::cerr << "rhs size: " << bv1.size() << '\n';
-    throw "unexpected size mismatch on verilog_case_equality";
+    error().source_location = expr.find_source_location();
+    error() << "unexpected size mismatch on verilog_case_equality:\n"
+            << "lhs: " << expr.lhs().pretty() << '\n'
+            << "lhs size: " << bv0.size() << '\n'
+            << "rhs: " << expr.rhs().pretty() << '\n'
+            << "rhs size: " << bv1.size() << eom;
+    throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_equality.cpp]: CHECK_RETURN.

File: src/solvers/flattening/boolbv_floatbv_op.cpp [hunk 24]
```diff
@@ -91,8 +90,9 @@ bvt boolbvt::convert_floatbv_op(const exprt &expr)
 
   if(op0.type()!=type || op1.type()!=type)
   {
-    std::cerr << expr.pretty() << '\n';
-    throw "float op with mixed types";
+    error().source_location = expr.find_source_location();
+    error() << "float op with mixed types:\n" << expr.pretty() << eom;
+    throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_floatbv_op.cpp]: DATA_INVARIANT.

**Review by martin-cs — CHANGES_REQUESTED** [review]
Worth doing and useful (although, wide change prone to breaking things, etc.).  However in a number of cases I think things should be invariants.  This will hopefully help with writing --validate as we will have made the requirements explicit.

File: src/goto-symex/goto_symex_state.cpp (hunk 10 above)
Comment (tautschnig) [reply src/goto-symex/goto_symex_state.cpp:58]: Good call - `git grep -w 'abort()'` should be reviewed, possibly as part of this PR?

File: src/goto-symex/goto_symex_state.cpp (hunk 14 above)
Comment (tautschnig) [reply src/goto-symex/goto_symex_state.cpp]: Yes, it is side-effect free (but quite costly, in actual fact).

**Comment by martin-cs** [comment]
> Good call - `git grep -w 'abort()'` should be reviewed, possibly as part of this PR?

If we're going to do that, then we should also check for exit...
Perhaps we could even add them to the linter to avoid them being added
in future.

File: src/goto-symex/goto_symex_state.cpp (hunk 12 above)
Comment (romainbrenguier) [reply src/goto-symex/goto_symex_state.cpp]: CHECK_RETURN ?

File: src/solvers/sat/pbs_dimacs_cnf.cpp [hunk 25]
```diff
@@ -45,7 +47,7 @@ void pbs_dimacs_cnft::write_dimacs_pb(std::ostream &out)
 
   for(const auto &lit_entry : pb_constraintmap)
   {
-    int dimacs_lit=lit_entry.first.dimacs();
+    int dimacs_lit = lit_entry.first.dimacs();
```
Comment (romainbrenguier) [inline src/solvers/sat/pbs_dimacs_cnf.cpp]: const

File: src/solvers/sat/pbs_dimacs_cnf.cpp [hunk 26]
```diff
@@ -99,80 +101,80 @@ bool pbs_dimacs_cnft::pbs_solve()
...
+#else
   command += " -z";
-  #endif
+#endif
 
   command += " -a > temp.out";
 
-  int res=system(command.c_str());
-  CHECK_RETURN(0==res);
+  int res = system(command.c_str());
```
Comment (romainbrenguier) [inline src/solvers/sat/pbs_dimacs_cnf.cpp]: const

File: src/solvers/sat/pbs_dimacs_cnf.cpp [hunk 27]
```diff
@@ -191,21 +193,18 @@ propt::resultt pbs_dimacs_cnft::prop_solve()
...
 
   // We start counting at 1, thus there is one variable fewer.
-  messaget::status() <<
-    (no_variables()-1) << " variables, " <<
-    clauses.size() << " clauses" << eom;
+  messaget::status() << (no_variables() - 1) << " variables, " << clauses.size()
+                     << " clauses" << eom;
 
-  bool result=pbs_solve();
+  bool result = pbs_solve();
```
Comment (romainbrenguier) [inline src/solvers/sat/pbs_dimacs_cnf.cpp]: const

File: src/solvers/sat/pbs_dimacs_cnf.cpp [hunk 28]
```diff
@@ -219,40 +218,40 @@ propt::resultt pbs_dimacs_cnft::prop_solve()
 
 tvt pbs_dimacs_cnft::l_get(literalt a) const
 {
-  int dimacs_lit=a.dimacs();
+  int dimacs_lit = a.dimacs();
 
   // std::cout << a << " / " << dimacs_lit << "=";
 
-  bool neg=(dimacs_lit < 0);
+  bool neg = (dimacs_lit < 0);
```
Comment (romainbrenguier) [inline src/solvers/sat/pbs_dimacs_cnf.cpp]: const

File: src/solvers/sat/pbs_dimacs_cnf.cpp [hunk 29]
```diff
@@ -219,40 +218,40 @@ propt::resultt pbs_dimacs_cnft::prop_solve()
...
-        }
+      // std::cout << "FALSE" << "\n";
+      return tvt(false);
     }
+    else
+    {
+      // std::cout << "TRUE" << "\n";
+      return tvt(true);
+    }
+  }
```
Comment (romainbrenguier) [inline src/solvers/sat/pbs_dimacs_cnf.cpp]: looks like these 25 lines could be replaced by `return tvt(neg == (f == assigned.end()))`

File: src/solvers/sat/pbs_dimacs_cnf.cpp [hunk 30]
```diff
@@ -69,18 +78,20 @@ bool pbs_dimacs_cnft::pbs_solve()
...
+  {
     command=getenv("PBS_PATH");
     }
     else
     {
     error ("Unable to read PBS_PATH environment variable.\n");
     return false;
     }
-  */
+#endif
```
Comment (romainbrenguier) [inline src/solvers/sat/pbs_dimacs_cnf.cpp]: looks like the indentation is wrong, and can't all this code be removed?

**Review by romainbrenguier — APPROVED** [review]

File: src/goto-symex/goto_symex_state.cpp (hunk 10 above)
Comment (tautschnig) [reply src/goto-symex/goto_symex_state.cpp:58]: #1902.

File: src/solvers/flattening/boolbv_equality.cpp (hunk 21 above)
Comment (peterschrammel) [reply src/solvers/flattening/boolbv_equality.cpp]: Using DATA_INVARIANT because CHECK_RETURN doesn't allow me to add an error message.

File: src/solvers/flattening/boolbv_floatbv_op.cpp (hunk 24 above)
Comment (peterschrammel) [reply src/solvers/flattening/boolbv_floatbv_op.cpp]: Using DATA_INVARIANT because CHECK_RETURN doesn't allow me to add an error message.

File: src/solvers/flattening/boolbv_equality.cpp (hunk 23 above)
Comment (peterschrammel) [reply src/solvers/flattening/boolbv_equality.cpp]: Using DATA_INVARIANT because CHECK_RETURN doesn't allow me to add an error message.

**Review by peterschrammel — COMMENTED** [review]
Also replaced spurious abort() and exit() calls.

**Comment by peterschrammel** [comment]
@martin-cs, please re-review.

File: src/solvers/flattening/boolbv_case.cpp [hunk 31]
```diff
@@ -49,15 +49,11 @@ bvt boolbvt::convert_case(const exprt &expr)
...
-      if(compare_bv.size()!=op.size())
-      {
-        std::cerr << "compare operand: " << compare_bv.size()
-                  << "\noperand: " << op.size() << '\n'
-                  << it->pretty()
-                  << '\n';
-
-        throw "size of compare operand does not match";
-      }
+      DATA_INVARIANT(
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_case.cpp:52]: I'm still not sure I agree with this.  CHECK_RETURN (as it's the return value of a previous call to convert) or INVARIANT (as a generic operational property of the algorithm).

File: src/solvers/flattening/boolbv_case.cpp [hunk 32]
```diff
@@ -68,15 +64,11 @@ bvt boolbvt::convert_case(const exprt &expr)
...
-      if(bv.size()!=op.size())
-      {
-        std::cerr << "result size: " << bv.size()
-                  << "\noperand: " << op.size() << '\n'
-                  << it->pretty()
-                  << '\n';
-
-        throw "size of value operand does not match";
-      }
+      DATA_INVARIANT(
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_case.cpp:67]: Same.

File: src/solvers/flattening/boolbv_cond.cpp [hunk 33]
```diff
@@ -51,15 +51,11 @@ bvt boolbvt::convert_cond(const exprt &expr)
...
-        if(bv.size()!=op.size())
-        {
-          std::cerr << "result size: " << bv.size()
-                    << "\noperand: " << op.size() << '\n'
-                    << it->pretty()
-                    << '\n';
-
-          throw "size of value operand does not match";
-        }
+        DATA_INVARIANT(
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_cond.cpp:54]: Same.

File: src/solvers/flattening/boolbv_equality.cpp [hunk 34]
```diff
@@ -43,14 +42,12 @@ literalt boolbvt::convert_equality(const equal_exprt &expr)
...
-  if(bv0.size()!=bv1.size())
-  {
-    std::cerr << "lhs: " << expr.lhs().pretty() << '\n';
-    std::cerr << "lhs size: " << bv0.size() << '\n';
-    std::cerr << "rhs: " << expr.rhs().pretty() << '\n';
-    std::cerr << "rhs size: " << bv1.size() << '\n';
-    throw "unexpected size mismatch on equality";
-  }
+  DATA_INVARIANT(
+    bv0.size() == bv1.size(),
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_equality.cpp:46]: Same.

File: src/solvers/flattening/boolbv_equality.cpp [hunk 35]
```diff
@@ -68,24 +65,23 @@ literalt boolbvt::convert_verilog_case_equality(
...
-  if(bv0.size()!=bv1.size())
-  {
-    std::cerr << "lhs: " << expr.lhs().pretty() << '\n';
-    std::cerr << "lhs size: " << bv0.size() << '\n';
-    std::cerr << "rhs: " << expr.rhs().pretty() << '\n';
-    std::cerr << "rhs size: " << bv1.size() << '\n';
-    throw "unexpected size mismatch on verilog_case_equality";
-  }
+  DATA_INVARIANT(
+    bv0.size() == bv1.size(),
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_equality.cpp:80]: Same.

File: src/solvers/flattening/boolbv_floatbv_op.cpp [hunk 36]
```diff
@@ -91,8 +91,10 @@ bvt boolbvt::convert_floatbv_op(const exprt &expr)
 
   if(op0.type()!=type || op1.type()!=type)
   {
-    std::cerr << expr.pretty() << '\n';
-    throw "float op with mixed types";
+    error().source_location=expr.find_source_location();
+    error() << "float op with mixed types:\n"
+            << expr.pretty() << eom;
+    throw 0;
```
Comment (martin-cs) [inline src/solvers/flattening/boolbv_floatbv_op.cpp]: DATA_INVARIANT

File: src/util/cmdline.cpp [hunk 37]
```diff
@@ -124,11 +122,8 @@ bool cmdlinet::parse(int argc, const char **argv, const char *optstring)
   {
     optiont option;
 
-    if(optstring[0]==':')
-    {
-      std::cerr << "cmdlinet::parse: Invalid option string\n";
-      abort();
-    }
+    DATA_INVARIANT(
+      optstring[0] != ':', "cmdlinet::parse: Invalid option string\n");
```
Comment (martin-cs) [inline src/util/cmdline.cpp:126]: Debatable invariant type...

**Review by martin-cs — APPROVED** [review]
I'd really like the last throw 0 converted to an invariant and we should chat about the last handful of debatable invariant types but these aren't blockers.
