### PR TITLE
C entry point generator: no unconditional conversion to pointer type

### LINKED ISSUE #6975: Crash on type error
CBMC version: 5.60.0
Operating system: MacOS 12.3.1 (intel)
Exact command line resulting in the issue: cbmc test.c
What behaviour did you expect: not a crash
What happened instead: 
```
CBMC version 5.60.0 (cbmc-5.60.0) 64-bit x86_64 macos
Parsing test.c
Converting
Type-checking test
--- begin invariant violation report ---
Invariant check failed
File: /tmp/cbmc-20220623-11094-1j0alae/src/util/pointer_expr.h:81 function: to_pointer_type
Condition: can_cast_type<pointer_typet>(type)
Reason: Precondition
Backtrace:
0   cbmc                                0x00000001049bd85a _Z15print_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 74
1   cbmc                                0x00000001049bdca1 _Z13get_backtracev + 42
```

Suppose I forgot the order and type of main's argc/argv arguments and instead used this wrong test.c:
```
int main(char *argv, int arc){
  return 0;
}
```
That's all it takes

### PR DESCRIPTION
**Pull request by tautschnig**
Do not try to create a pointer_typet when the type might not actually be
a pointer type. This was triggerable by syntactically well-formed C
input and should instead be handled by a user-facing error message.

Fixes: #6975

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/ansi-c/ansi_c_entry_point.cpp [hunk 1]
```diff
@@ -248,7 +248,10 @@ bool generate_ansi_c_start_function(
     {
       // ok
     }
-    else if(parameters.size()==2 || parameters.size()==3)
+    else if(
+      parameters.size() >= 2 && parameters[1].type().id() == ID_pointer &&
```
Comment (kroening) [inline src/ansi-c/ansi_c_entry_point.cpp:258]: Did you mean `parameters[0]`?

Comment (tautschnig) [reply src/ansi-c/ansi_c_entry_point.cpp:258]: No, `parameters[0]` is what we'd expect to be `argc` if I' not mistaken?

Comment (TGWDB) [reply src/ansi-c/ansi_c_entry_point.cpp:258]: This looks wrong because the regression test has `(char *argv, int argc)` but the CBMC code is expecting/assuming the parameters in the other order. Is there a place where the code rewrites/forces the order, or is this actually entirely up to the code being sent to CBMC? If the former, a comment would clarify this, if the latter, then this code makes assumptions that may be wrong.

Comment (tautschnig) [reply src/ansi-c/ansi_c_entry_point.cpp:258]: The one place that enforces the order is the C standard (and any related architecture descriptions). The user, however, may supply arbitrary (syntactically valid) C code, even one that does not respect the calling conventions set out in the C standard. If the user does supply such code (as is done in the accompanying regression test), then we can only tell them that they got it wrong, which is what we do via the error message in the `else` branch of this code. The change being proposed here should make sure that we do end up in this `else` branch.

Does this address your concern? Should I still be making changes to the implementation? Should I perhaps add the above as a comment?

Comment (TGWDB) [reply src/ansi-c/ansi_c_entry_point.cpp:258]: Yes, I'm happy to approve. The detail in your response might be nice to have in the comments though since this is not immediately clear.

**Review by TGWDB — APPROVED** [review]

File: src/ansi-c/ansi_c_entry_point.cpp (hunk 1 above)
Comment (tautschnig) [reply src/ansi-c/ansi_c_entry_point.cpp:258]: Comment added to the code.

Comment (nwetzler) [reply src/ansi-c/ansi_c_entry_point.cpp:258]: The comment is very helpful.

File: regression/ansi-c/main1/test.desc [hunk 2]
```diff
@@ -0,0 +1,8 @@
+CORE test-c++-front-end
+main.c
+
+'main' with signature 'signed int \(char \*argv, signed int arc\)' found
+^EXIT=(64|1)$
+^SIGNAL=0$
+--
+Invariant check failed
```
Comment (nwetzler) [inline regression/ansi-c/main1/test.desc:8]: Can we add a description of what the test is trying to achieve?  Maybe something like:
> In this test, we detect a non-standard C entry point and gracefully exit with a message to the user.

**Review by nwetzler — APPROVED** [review]
This looks like a great solution.  Only suggestion would be to add more detail to the regression test about what the test is aiming to achieve.

File: regression/ansi-c/main1/test.desc (hunk 2 above)
Comment (tautschnig) [reply regression/ansi-c/main1/test.desc:8]: Thank you, done!

**Review by kroening — APPROVED** [review]
