### PR TITLE
Java object factory: allocate fixed length arrays

### LINKED ISSUE #746: Consider bounded rather than variable-length arrays for Java nondet inputs
A while ago I wrote code to populate arrays which are (direct or indirect) arguments to a Java entry point. For example:

```
class A {
  int[] arr1;
}

class B {
  void testme(A a, long[] arr2) { ... }
}
```

In this case with `--function B.testme`, an array will be nondeterministically populated for both direct parameter `arr2` and indirect parameter `arr1`.

It's done by generating a nondet int for the array's length, using `ASSUME` statements to bound it to be >= 0 and <= the command line argument `java-max-input-array-length` (default 5). Then if that variable were named `nondet_arr_length` a `cpp_new` allocation is generated with type `int[nondet_arr_length]` and compiled.

This results in a large number of constraints being generated, because the array theory required to describe the effects of a series of array operations is quite verbose. By contrast when the array has a fixed known dimension it can simply be decomposed into a finite if-statement casing over the possibilities (so x[y] = 1 becomes "y == 0 : x_0 = 1 : y == 1 ? x_1 = 1 : ...)

In the Java case we often (nearly always?) have a low upper bound on such arrays' lengths. Therefore I suggest we should investigate the effects on formula complexity of *always* allocating the maximum given array length, resulting in only slight waste in that conditionals will be introduced that can never be satisifed (e.g. idx == 4 ? ... when the actual array length doesn't allow that), compared to the always-expensive variable-length array theory.

### PR DESCRIPTION
**Pull request by smowton**
This replaces the variable-length arrays produced by the Java object factory with fixed-length ones annotated with a variable length member. This allows the backend to use the much cheaper fixed-length array lowering rather than the full variable-length array theory, while retaining the ability for the effective length to vary. In effect this creates a bounded-length array construct.

Fixes #746

### CODE REVIEW

File: src/java_bytecode/java_object_factory.cpp [hunk 1]
```diff
@@ -386,6 +386,7 @@ void java_object_factoryt::gen_nondet_array_init(
 
   side_effect_exprt java_new_array(ID_java_new_array, expr.type());
   java_new_array.copy_to_operands(length_sym_expr);
+  java_new_array.set(ID_length_upper_bound, max_length_expr);
```
Comment (tautschnig) [inline src/java_bytecode/java_object_factory.cpp]: Couldn't we then also get rid of other bits of code using `max_length_expr`?

Comment (smowton) [inline src/java_bytecode/java_object_factory.cpp]: `length_sym_expr`? No, the idea is that `length_sym_expr` is the actual size of the array and `max_length_expr` is the upper bound on that length. The actual size is used to initialise the array with NONDET members, and the bound is used to allocate the storage and provide a bound on the initialisation loop.

Comment (tautschnig) [inline src/java_bytecode/java_object_factory.cpp]: Ah, of course.
