### PR TITLE
Floating-point normalization must not overflow

### LINKED ISSUE #7616: Converting a positive subnormal double to float yields +infinity
CBMC version: 5.79.0
Operating system: Linux x86_64
Exact command line resulting in the issue: cbmc main.c --trace
What behaviour did you expect: verification successful
What happened instead: verification failed with an incorrect trace

The example program is
```
int main() {
  float f;
  double d;
  if(d > 0.0 && d < 1.0) {
    f = d;
    __CPROVER_assert(f <= 1.0f, "limited");
  }
  return 0;
}
```
CBMC reports a failure for the assertion. In the trace (see attached trace.log), d is shown as a positive subnormal number and f is shown as positive infinity:
```
State 12 file d2f.c function main line 3 thread 0
----------------------------------------------------
  d=5.562684e-309 (00000000 00000011 11111111 11111111 11111110 00000100 00000000 00000000)

State 14 file d2f.c function main line 5 thread 0
----------------------------------------------------
  f=+INFINITY (01111111 10000000 00000000 00000000)
```

If d is restricted to normal numbers, the assertion passes.
Not every subnormal number converts to +infinity.
If the assertion is changed to state that f is in the expected range or positive infinity, it passes:
```
 __CPROVER_assert((f >= 0 && f <= 1.0f) || (isinf(f) && f > 0), "limited"); // this passes
```

[main.c.txt](https://github.com/diffblue/cbmc/files/11059827/main.c.txt)
[trace.log](https://github.com/diffblue/cbmc/files/11059840/trace.log)

### PR DESCRIPTION
**Pull request by tautschnig**
We need to extend the exponent to compute a new exponent without
overflow; subsequent denormalization and rounding will ensure the
exponent fits into the target format.

Fixes: #7616

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/solvers/floatbv/float_utils.cpp [hunk 1]
```diff
@@ -195,6 +195,7 @@ bvt float_utilst::conversion(
     if(dest_spec.e > spec.e)
     {
       normalization_shift(result.fraction, result.exponent);
+      result.exponent.resize(dest_spec.e);
```
Comment (kroening) [inline src/solvers/floatbv/float_utils.cpp:201]: Can you explain that one?

**Comment by kroening** [comment]
May I ask you to check whether the world-level flattening implementation in `solvers/floatbv/float_bv.cpp` does the same mistake?

File: src/solvers/floatbv/float_utils.cpp (hunk 1 above)
Comment (tautschnig) [reply src/solvers/floatbv/float_utils.cpp:201]: Comment added.

**Comment by tautschnig** [comment]
> May I ask you to check whether the world-level flattening implementation in `solvers/floatbv/float_bv.cpp` does the same mistake?

Oh, thank you, indeed! Having put the fix in place makes the regression test pass when using Z3 (or any other SMT back-end that doesn't support FPA).

**Review by kroening — APPROVED** [review]
