### PR TITLE
Pointer-primitive checks should succeed for valid pointers at object bound

### LINKED ISSUE #7064: `--pointer-primitive-check` fails on `__CPROVER_r_ok(ptr, 0)` when `ptr = malloc(0)`
CBMC version: 5.62
Operating system: linux/macos
Exact command line resulting in the issue: `cbmc --pointer-check --pointer-overflow-check --pointer-primitive-check"
What behaviour did you expect: success
What happened instead: failed proof obligations

I ran into this issue while writing a custom stub for `memcpy`, by copying the CPROVER library function and modifying it slightly :

```c
#include <stdlib.h>
#include <string.h>

#undef memcpy
void *memcpy(void *dst, const void *src, size_t n)
{
  __CPROVER_precondition(
    __CPROVER_POINTER_OBJECT(dst) != __CPROVER_POINTER_OBJECT(src) ||
      ((const char *)src >= (const char *)dst + n) ||
      ((const char *)dst >= (const char *)src + n),
    "memcpy src/dst overlap");
  __CPROVER_precondition(
    __CPROVER_r_ok(src, n), "memcpy source region readable");
  __CPROVER_precondition(
    __CPROVER_w_ok(dst, n), "memcpy destination region writeable");

  if(n > 0)
  {
    // library code
    // char src_n[n];
    //  __CPROVER_array_copy(src_n, (char *)src);
    // __CPROVER_array_replace((char *)dst, src_n);

    // modified code
    __CPROVER_havoc_slice(dst, n);
  }

  return dst;
}


int main() {
  size_t src_size;
  size_t dest_size;
  __CPROVER_assume(dest_size >= src_size);
  char *src = malloc(src_size);
  __CPROVER_assume(src);
  char *dest = malloc(dest_size);
  __CPROVER_assume(dest);
  memcpy(dest,src,src_size);
}
```

```
cbmc memcpy.c

** Results:
<builtin-library-malloc> function malloc
[malloc.assertion.1] line 28 max allocation size exceeded: SUCCESS
[malloc.assertion.2] line 33 max allocation may fail: SUCCESS

memcpy.c function main
[main.precondition_instance.1] line 39 memcpy src/dst overlap: SUCCESS
[main.precondition_instance.2] line 39 memcpy source region readable: SUCCESS
[main.precondition_instance.3] line 39 memcpy destination region writeable: SUCCESS

memcpy.c function memcpy
[memcpy.assertion.1] line 25 assertion havoc_slice W_OK(dst, n): SUCCESS

** 0 of 6 failed (1 iterations)
VERIFICATION SUCCESSFUL
```

VS this with pointer primitive checks enabled

```
cbmc memcpy.c --pointer-primitive-check
** Results:
<builtin-library-malloc> function malloc
[malloc.assertion.1] line 28 max allocation size exceeded: SUCCESS
[malloc.assertion.2] line 33 max allocation may fail: SUCCESS

memcpy.c function main
[main.precondition_instance.1] line 39 memcpy src/dst overlap: SUCCESS
[main.precondition_instance.2] line 39 memcpy source region readable: SUCCESS
[main.precondition_instance.3] line 39 memcpy destination region writeable: SUCCESS

memcpy.c function memcpy
[memcpy.pointer_primitives.1] line 13 pointer invalid in R_OK((const void *)src, src_size): SUCCESS
[memcpy.pointer_primitives.2] line 13 deallocated dynamic object in R_OK((const void *)src, src_size): SUCCESS
[memcpy.pointer_primitives.3] line 13 dead object in R_OK((const void *)src, src_size): SUCCESS
[memcpy.pointer_primitives.4] line 13 pointer outside object bounds in R_OK((const void *)src, src_size): FAILURE
[memcpy.pointer_primitives.5] line 15 pointer invalid in W_OK((void *)dest, src_size): SUCCESS
[memcpy.pointer_primitives.6] line 15 deallocated dynamic object in W_OK((void *)dest, src_size): SUCCESS
[memcpy.pointer_primitives.7] line 15 dead object in W_OK((void *)dest, src_size): SUCCESS
[memcpy.pointer_primitives.8] line 15 pointer outside object bounds in W_OK((void *)dest, src_size): FAILURE
[memcpy.assertion.1] line 25 assertion havoc_slice W_OK(dst, n): SUCCESS

** 2 of 14 failed (3 iterations)
VERIFICATION FAILED
```

All CPROVER library functions check  pointer validity using `__CPROVER_r_ok(src,n)`. These preconditions do not seem to trigger `--pointer-primitive-checks` (likely because the library is linked after pointer primitive checks instantiation)

However, the preconditions written in user stubs (or function and loop contracts) do trigger `--pointer-primitive-checks` and cause failures.

The failures are due to pointers resulting from `char *src = malloc(0);`  causing  `pointer outside object bounds` errors on statements like  `__CPROVER_precondition(__CPROVER_r_ok(src, 0));`.

This is what the C11 standard says in section 7.21.1 about string function conventions:

```
Where an argument declared as size_t n specifies the length of the array for a
function, n can have the value zero on a call to that function. Unless explicitly stated
otherwise in the description of a particular function in this subclause, pointer arguments
on such a call shall still have valid values, as described in 7.1.4. On such a call, a
function that locates a character finds no occurrence, a function that compares two
character sequences returns zero, and a function that copies characters copies zero
characters.
```

And 7.1.4 says the following:

```
If an argument to a function has an invalid value (such as a value outside the domain
of the function, or a pointer outside the address space of the program, or a null pointer, 
or a pointer to non-modifiable storage when the corresponding parameter is not const-qualified) 
or a type (after promotion) not expected by a function with variable number of arguments,
the behavior is undefined.
```

If I understand the standard correctly,  if `malloc(0)` does not return NULL, the pointer should be considered as valid and should not cause UB in string functions as long as the `n` parameter is `0`.

This in turn leads me to think that pointer primitive checks should not fail on `__CPROVER_r_ok(ptr, 0)` when `ptr` is a non-NULL value returned by `malloc(0)`.

One way around it could be to disable the checks using `#pragmas CPROVER disable "pointer-primitive"`  or writing preconditions as `size == 0 || __CPROVER_r_ok(src, size)` everywhere, but this is very cumbersome.

How about modifying pointer primitive checks to accept cases that the C standard says are acceptable ?

### PR DESCRIPTION
**Pull request by tautschnig**
The C standard designates the pointer with offset object size (pointing to the first byte outside the object) to be valid. In keeping with this, `--pointer-primitive-check` should not designate this as invalid (even when reading non-zero bytes from this object is).

Fixes: #7064

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: regression/cbmc/pointer-primitive-check-05/main.c [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#include <stdlib.h>
+
+int main()
+{
+  unsigned char s;
```
Comment (jimgrundy) [inline regression/cbmc/pointer-primitive-check-05/main.c]: I guess using an unsigned char limits the size here. Should we be using a size_t that is assumed to be less than max_malloc_size ... or maybe we don't even need that since malloc should just return null if we ask for something too big.

**Review by jimgrundy — APPROVED** [review]

File: regression/cbmc/pointer-primitive-check-05/main.c (hunk 1 above)
Comment (tautschnig) [reply regression/cbmc/pointer-primitive-check-05/main.c]: Yes, this was meant to limit the size and avoid running into those other problems. But, as you said, it should actually be ok to face these problems. So I've revised this back to your original example and use `size_t`.

**Comment by jimgrundy** [comment]
Assigning @kroening as the only active owner (other than the author) for the code in question.

File: regression/cbmc/pointer-primitive-check-03/main.c [hunk 2]
```diff
@@ -22,7 +22,8 @@ void main()
   // offset out of bounds
   char *p5 = malloc(10);
   p5 += 10;
-  __CPROVER_r_ok(p5, 1);
+  _Bool result = __CPROVER_r_ok(p5, 1);
+  __CPROVER_assert(!result, "should be false");
```
Comment (kroening) [inline regression/cbmc/pointer-primitive-check-03/main.c:27]: This test only indirectly relates to the pointer primitive checks -- I'd put it into pointer-predicates/

File: regression/cbmc/pointer-primitive-check-05/main.c [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+  size_t s;
+  char *p = malloc(s);
+  // at __CPROVER_max_malloc_size p + s would overflow; all larger values of s
+  // make malloc return NULL when using --malloc-fail-null
+  if(p != NULL && s != __CPROVER_max_malloc_size)
+  {
+    char *q = p + s;
+    __CPROVER_assert(__CPROVER_r_ok(q, 0), "should be valid");
+    __CPROVER_assert(!__CPROVER_r_ok(q + 1, 0), "should fail");
+  }
```
Comment (kroening) [inline regression/cbmc/pointer-primitive-check-05/main.c]: Same for this one

**Review by kroening — APPROVED** [review]

File: regression/cbmc/pointer-primitive-check-05/main.c (hunk 3 above)
Comment (tautschnig) [reply regression/cbmc/pointer-primitive-check-05/main.c]: Done (actually put it in `pointer-predicates/`).

File: regression/cbmc/pointer-primitive-check-03/main.c (hunk 2 above)
Comment (tautschnig) [reply regression/cbmc/pointer-primitive-check-03/main.c:27]: Done (though I have instead chosen `r_w_ok10`).
