### PR TITLE
expr2bits needs to handle pointer case

### LINKED ISSUE #4168: Regression: CBMC crashes because it passes the string "NULL" get_bvrep_bit during symex
Observed on: 3b7d59af5ff55e2135b6308022aa2ce5e99fd374
Still working on: 9cf2bfb3e458d419d842a0e1fd26fb1748451851

(approximate range, haven't bisected yet)

CBMC fails with:

```
Invariant check failed
File: ../src/util/arith_tools.cpp:305 function: get_bvrep_bit
Condition: isdigit(nibble) || (nibble >= 'A' && nibble <= 'F')
Reason: bvrep is hexadecimal, upper-case
```

For some reason the `src` parameter ends up being the string `"NULL"` when running `cbmc` against the following example:

```
#include <assert.h>
#include <stddef.h>

struct linked_list {
  struct linked_list *next;
};


int main(void) {
  size_t list_sz = 8ul;
  assert(list_sz == sizeof(struct linked_list));
  struct linked_list *list = malloc(list_sz);
  list->next = (struct linked_list *)0;
}
```

This does _not_ happen when `8ul` above is replaced with `sizeof(struct linked_list)`. It also didn't happen last year, so was presumably caused by some of the recent refactoring work.

### PR DESCRIPTION
**Pull request by kroening**
This fixes #4168. The pointer case was not handled.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/util/simplify_expr.cpp [hunk 1]
```diff
@@ -1753,6 +1753,13 @@ optionalt<std::string> simplify_exprt::expr2bits(
 
       return result;
     }
+    else if(type.id() == ID_pointer)
+    {
+      if(value == ID_NULL)
```
Comment (tautschnig) [inline src/util/simplify_expr.cpp]: `if(value == ID_NULL && config.ansi_c.NULL_is_zero)`

**Review by tautschnig — CHANGES_REQUESTED** [review]
The test has a further problem (I should have noticed when reviewing...): it needs 's/#include <stddef.h>/#include <stdlib.h>/'. Then CI should be happy.

**Comment by kroening** [comment]
@tautschnig Yes, but that problem's a bug. I'll add the #include for this test, and will make a new one without.

**Review by tautschnig — APPROVED** [review]

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0c22c0324b6230efc854caa83db395faf0c82631).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/101218184
