### PR TITLE
Translate exceptions from C++ API into Rust `Result` types.

### LINKED ISSUE #7490: Handling of exceptions in the new Rust API
(This item is to track feature development across the new Rust API for CBMC)

As it stands, exceptions from within CBMC are propagating upwards to the Rust API, causing it to crash when an exception is raised.

[`cxx.rs`](https://cxx.rs) allows for exceptions to be handled in a way that translates the raised exception to a Rust `Result<T, E>` type.

This piece of work is about utilising this capability of `cxx.rs` to make the Rust API more robust and well-behaved.

### PR DESCRIPTION
**Pull request by NlightNFotis**
This PR is adding the capacity to the Rust API to translate exceptions from C++'s
end into Rust `Result` types that make handling of exceptions more robust and
ergonomic.

The last commit is not strictly related to the PR (it's a format using `cargo fmt`),
but I hadn't run it against this project yet, so this is including it so that it
starts being formatted and consistent with `rust fmt`.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/libcprover-rust/src/lib.rs [hunk 1]
```diff
@@ -119,10 +131,18 @@ mod tests {
         let vect = ffi::translate_vector_of_string(vec);
         assert_eq!(vect.len(), 1);
 
-        client.load_model_from_files(vect);
+        if let Err(_) = client.load_model_from_files(vect) {
+            println!("Panicking: load_model_from_files_failed");
```
Comment (TGWDB) [inline src/libcprover-rust/src/lib.rs]: Why does this one panic, but not others?

File: src/libcprover-rust/include/c_api.h [hunk 2]
```diff
@@ -16,3 +18,22 @@ translate_vector_of_string(rust::Vec<rust::String> elements);
...
+  namespace behavior {
+
+    template <typename Try, typename Fail>
+    static void trycatch(Try &&func, Fail &&fail) noexcept {
+      try {
+        func();
+      } catch (const cprover_exception_baset &e) {
+        fail(e.what());
+      } catch (const invariant_failedt &i) {
+        fail(i.what());
```
Comment (TGWDB) [inline src/libcprover-rust/include/c_api.h]: I thought we had preferred project style to use longer and clearer names than `e` and `i`.

File: src/libcprover-rust/src/lib.rs [hunk 3]
```diff
@@ -119,10 +131,18 @@ mod tests {
...
+            process::exit(1);
+        }
         // Perform a drop of any unused functions.
-        client.drop_unused_functions();
+        if let Err(err) = client.drop_unused_functions() {
+            eprintln!("Error during client call: {:?}", err);
+            process::exit(1);
+        }
 
+        println!("Just before we print the messages");
```
Comment (TGWDB) [inline src/libcprover-rust/src/lib.rs]: Leftover debug code?

File: src/libcprover-rust/src/lib.rs [hunk 4]
```diff
@@ -87,8 +99,17 @@ mod tests {
...
+        // ATTENTION: The following `.clone()` is unneeded - I keep it here in order to
+        // make potential printing of the message buffer easier (because of borrowing).
+        // This is also why a print instruction is commented out (as a guide for someone
+        // else in case they want to inspect the output).
+        let validation_msg = "Validating consistency of goto-model supplied to API session";
         let msgs = ffi::get_messages();
-        print_response(msgs);
+        let msgs_assert = translate_response_buffer(msgs).clone();
+
+        assert!(msgs_assert.contains(&String::from(validation_msg)));
```
Comment (TGWDB) [inline src/libcprover-rust/src/lib.rs:109]: I recognise this is in test code and so not that significant, but it would be much nicer if `validate_goto_model()` actually returned a useful value instead of needing to string match over a collection of strings.

File: src/libcprover-rust/src/lib.rs [hunk 5]
```diff
@@ -113,8 +134,12 @@ mod tests {
             process::exit(1);
         }
 
+        let verification_msg = "VERIFICATION FAILED";
+
         let msgs = ffi::get_messages();
-        print_response(msgs);
+        let msgs_assert = translate_response_buffer(msgs).clone();
+        
+        assert!(msgs_assert.contains(&String::from(verification_msg)));
```
Comment (TGWDB) [inline src/libcprover-rust/src/lib.rs]: As above, better to get something useful back.

File: src/libcprover-rust/src/lib.rs (hunk 4 above)
Comment (NlightNFotis) [reply src/libcprover-rust/src/lib.rs:109]: Yeah, this is very hard to do right now - the C++ API returns `void`, and that's also because the function it's delegating to, `validate_goto_model` in `src/goto-programs/validate_goto_model.cpp:128` is also `void`.

This will require some deep refactoring for these to behave this way.

The assertions I have added are along the lines of "Test for behaviour - not interface", which are just making sure that a side-effect of the action has been performed accurately.

Not terribly robust tests, but better than nothing - until at least a better interface presents itself.

File: src/libcprover-rust/src/lib.rs (hunk 3 above)
Comment (NlightNFotis) [reply src/libcprover-rust/src/lib.rs]: Yeah, this was removed in the next commit.

File: src/libcprover-rust/src/lib.rs (hunk 1 above)
Comment (NlightNFotis) [reply src/libcprover-rust/src/lib.rs]: This is experimental code that I failed to remove 🤦🏻‍♂️

Technically, when an `assert!` macro fails, it calls `panic!` - I wanted to simulate this behaviour manually (or at least approximate part of it) and then I forgot to remove it.

File: src/libcprover-rust/src/lib.rs (hunk 4 above)
Comment (TGWDB) [reply src/libcprover-rust/src/lib.rs:109]: Understood that this is test code and proper result structures are future work.

**Review by TGWDB — APPROVED** [review]
