### PR TITLE
Fix SMT2 output determinism by using ordered maps

### LINKED ISSUE #8820: Proof instability resulting from insertion of blank line in sources
In the mlkem-native project, we have found that addition of blank lines in source code can cause unexpected differences in generated GOTO and SMT files, and subsequent proof instability.

This Issue documents this problem and adds a tiny test case that demonstrates one such difference. This may not be the _only_ source of such instability, but this test case serves as a starting point to understand the issues.

Link to test case sources will be added below.

### PR DESCRIPTION
**Pull request by tautschnig**
This commit addresses the issue where SMT2 formula output varied even when semantically equivalent C code was provided with different source formatting (e.g., adding empty lines).

Root Cause:
-----------
Phi nodes were generated by iterating over a hash map, implying iteration in hash-dependent order. When source code formatting changes:
1. Line numbers change
2. Expression hashes change
3. Symbols are stored/iterated in different orders
4. SMT2 declarations appear in different orders

The ensuing changes to the SMT formula content -- even though the formulae were semantically equivalent -- caused variability in SMT-solver performance. Producing stable output should ensure stability in solver performance. For the test case provided in #8820 this now yields: `SMT files: 0 lines differ` (where previously it was 8 lines differing).

Fixes: #8820

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by rod-chapman** [comment]
Test results on mlkem-native, running on M1 macOS, with MLKEM_K=4 and -j8

Before (release 6.8.0): 139 proofs in 17m13s real, 49m 12s user
After (this branch): 139 proofs in 18m39s real, 51m users.

**Comment by rod-chapman** [comment]
Test results on mlkem-native, running on r7g.16xlarge/Ubuntu, with MLKEM_K=4 and -j64

Before (release 6.8.0): 139 proofs in 6m20s real, 47m37s user
After (this branch): 139 proofs in 6m53s real, 49m33s user.

**Comment by rod-chapman** [comment]
Test results on mldsa-native, running on r7g.16xlarge/Ubuntu, with MLD_CONFIG_PARAMETER_SET=87 and -j64

Before (release 6.8.0): 173 proofs in 4m22s real, 51m38s user
After (this branch): 173 proofs in 5m49s real, 57m28s

so a little slower. For example, the proofs of sign_verify_internal slows from 143s to 307s.

With stability gained, we can experiment with that to see which ordering of SMT terms is the best.

I also hope that PR#8705 will result in a noticeable improvement in performance.

**Comment by kroening** [comment]
Rod: can you tell what makes that run slower? Is it the time to generate the SMT-LIB instance, or the time to solve it?

**Comment by rod-chapman** [comment]
For polyvec_add() which slowed a little after this change, the time to generate the SMT is 5 seconds. Time to prove it with Z3 is 520s.

Once we have stabilized SMT-generation in CBMC, we've got a rational basis to proceed - we can experiment with Z3 options and tactics, work out what the best ordering of terms is (for Z3 at least), and possible open bug reports on Z3. Onwards!

**Comment by rod-chapman** [comment]
That Z3 time of 520s is with the option `rewrite.sort_bv_ac=true`.

With default options, proof time is 44s on my laptop. There might be a few other cases where we can adjust Z3 options to get the overall performance back to what it was.

**Comment by rod-chapman** [comment]
Do we know why CI is failing?

**Comment by rod-chapman** [comment]
With the latest commit: result for mlkem-native proofs on r7g, 64 cores, with MLKEM_K=4

CBMC 6.8.0 - 151 proofs OK in 6m20s real, 48m2s user
This branch - 151 proofs OK in 7m2s real, 50m35s user

**Comment by rod-chapman** [comment]
With the latest commit: result for mldsa-native (main branch) proofs on r7g, 64 cores, with MLDSA_CONFIG_PARAMETER_SET=87

CBMC 6.8.0 - 174 proofs OK in  3m56s real,  52m24s user
This branch - 174 proofs OK in 4m55s real, 55m54s user

The most obvious drop in performance is in sign_verify_internal() function, where proof time slows from 120s to 260s with the new branch.

**Comment by tautschnig** [comment]
I need to fix up some regression tests that expect a particular instruction numbering.

**Comment by rod-chapman** [comment]
**mlkem-native,K=4,r7g,AArch64/Ubuntu,64 cores**

CBMC 6.8.0, 151 proofs in 6m29s real, 49m40s user. Longest are indcpa_keypair_derand@348s, indcpa_enc@250s
CBMC commit c596, 151 proofs in 17m3s real, 65m45s user. Longest are indcpa_enc@986s, indcpa_keypair_derand@297s

Odd...

indcpa_enc has slowed from 250s to 986s
indcpa_keypair_derand got faster from 348s to 297s

File: src/util/simplify_expr.cpp [hunk 1]
```diff
@@ -1012,6 +1012,45 @@ simplify_exprt::simplify_typecast(const typecast_exprt &expr)
     }
   }
 
+  // Push a pointer typecast into pointer arithmetic
```
Comment (kroening) [inline src/util/simplify_expr.cpp]: Is that even related?

Comment (tautschnig) [reply src/util/simplify_expr.cpp]: See [the commit message](https://github.com/diffblue/cbmc/pull/8830/changes/c59610ecefb22ac1a17cf8e8ae9d68d59e34dd22): sort-of in that it avoids producing different-looking formulae that are still semantically equivalent. But it's indeed not a problem caused by iteration over hash maps. I can move this to a different PR if preferred.

**Comment by rod-chapman** [comment]
With the latest commit: result for mlkem-native proofs on r7g, 64 cores, with MLKEM_K=4

Last test run - 151 proofs OK in 7m2s real, 50m35s user
This branch @ 37f2... - 151 proofs OK in 16m55s real, 63m29s

The tall poppy is indcpa_enc() at 982s. The next longest is 300s, so I will look at that one to see if it can brought back under control.

**Comment by rod-chapman** [comment]
With the latest commit: result for mldsa-native (main branch) proofs on r7g, 64 cores, with MLDSA_CONFIG_PARAMETER_SET=87

Last test run - 174 proofs OK in 4m55s real, 55m54s user
Latest commit on this branch: 174 proofs OK in 4m31s 54m44s

so a bit faster.

**Comment by rod-chapman** [comment]
I can confirm that using z3 tactic.default_tactic=smt reduces the proof time of indcpa_enc() to 300s with MLKEM_K=4 on r7g/Ubuntu, which I hope is acceptable.

File: src/util/simplify_expr.cpp (hunk 1 above)
Comment (kroening) [reply src/util/simplify_expr.cpp]: Yes, please!

**Review by kroening — APPROVED** [review]

File: src/util/simplify_expr.cpp (hunk 1 above)
Comment (tautschnig) [reply src/util/simplify_expr.cpp]: Done: https://github.com/diffblue/cbmc/pull/8836

**Review by feliperodri — APPROVED** [review]
All the changes in the dynamic frame portion LGTM. 🚢 it!
