### PR TITLE
Fixup GCC 12 errors

### LINKED ISSUE #7663: Build fails when using GCC 12
CBMC build fails when using GCC 12 (latest version of GCC released in August 2022) on builds not using `-O` directives (meaning `-O0`).

Multiple new `return-type` warnings are produced when building with GCC 12.
This makes the build to fail as we use -Werror.

```
cbmc/src/util/interval.cpp: In static member function 'static exprt constant_interval_exprt::get_extreme(std::vector<exprt>, bool)':
cbmc/src/util/interval.cpp:567:1: error: control reaches end of non-void function [-Werror=return-type]
  567 | }
      | ^
cc1plus: all warnings being treated as errors
```

```
cbmc/src/util/simplify_expr_int.cpp: In member function 'simplify_exprt::resultt<> simplify_exprt::simplify_inequality_both_constant(const binary_relation_exprt&)':
cbmc/src/util/simplify_expr_int.cpp:1533:1: error: control reaches end of non-void function [-Werror=return-type]
 1533 | }
      | ^
```

It is possible that other files belonging to other submodules also fail, but the build failure stops the build earlier.

When building with CMake, it is possible to reproduce this by using `Debug` as `CMAKE_BUILD_TYPE` (`cmake -DCMAKE_BUILD_TYPE=Debug ..`).

Note that the error is not related with the addition of `-DNDEBUG`, but appears **ONLY** when `-O0` is passed (or no `-O` directives are passed).

CBMC version: 5.80.0
Operating system: Ubuntu 22.04, MacOS, Fedora
Exact command line resulting in the issue: make
What behaviour did you expect: build succeed
What happened instead: build failure

### PR DESCRIPTION
**Pull request by esteffin**
GCC 12 when using `-O0` fails because of a missing-return-statement warning caused by the implementation of `INVARIANT(false)`.

This is because the condition `if (true)` is not considered exahustive.

The solution involves marking the unreachable path as `__builtin_unreachable()`.

This PR also replaces some `INVARIANT(false, REASON)` statement used to have `UNREACHABLE`, but with a reason.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/util/invariant.h [hunk 1]
```diff
@@ -500,9 +500,26 @@ CBMC_NORETURN void report_invariant_failure(
...
 
 /// This should be used to mark dead code
-#define UNREACHABLE INVARIANT(false, "Unreachable")
-#define UNREACHABLE_STRUCTURED(TYPENAME, ...)                                  \
-  EXPAND_MACRO(INVARIANT_STRUCTURED(false, TYPENAME, __VA_ARGS__))
+#ifdef __GNUC__
+// GCC 12 with -O0 fails reporting missing return when using UNREACHABLE.
+// Using __builtin_unreachable fixes this without breaking the invariant.
+#  define UNREACHABLE                                                          \
+    do                                                                         \
```
Comment (NlightNFotis) [inline src/util/invariant.h:507]: Why do we need a new `do ... while(false)` block here? The `INVARIANT` definition has one of its own.

Would it make more sense to just have a block `{ INVARIANT(false, "Unreachable"); __builtin_unreachable(); }` or am I mistaken?

Comment (esteffin) [reply src/util/invariant.h:507]: The `do { ... } while (false)` in the macros is because it allows a `;` (semicolon) after the macro, but does not require it (it works with both).

It is a common C methodology.

**Review by kroening — APPROVED** [review]

**Review by NlightNFotis — APPROVED** [review]

File: src/util/invariant.h [hunk 2]
```diff
@@ -500,9 +500,33 @@ CBMC_NORETURN void report_invariant_failure(
...
+    {                                                                          \
+      INVARIANT(false, "Unreachable");                                         \
+      __builtin_unreachable();                                                 \
```
Comment (tautschnig) [inline src/util/invariant.h:510]: Shouldn't we instead be adding this to the expansion of the `INVARIANT` macro?

**Review by peterschrammel — APPROVED** [review]

File: src/util/invariant.h (hunk 2 above)
Comment (esteffin) [reply src/util/invariant.h:510]: No as the invariant can actually be satisfied (`INVARIANT(condition, "some reason")` succeed when `condition` is `true`).

The problem is just related to GCC 12 with `-O0` refusing to statically resolve cases of the form `if (true) { <terminate> }`.

The only cases I found of this are `UNREACHABLE`, `UNIMPLEMENTED_FEATURE` and some `INVARIANT(false, "unreachable because")` and they have all been fixed.

Comment (tautschnig) [reply src/util/invariant.h:510]: What I meant was putting the `__builtin_unreachable()` inside the `if(!(CONDITION))` branch, which wouldn't have the problem of the invariant being satisfied. Wouldn't that have worked? (It's possible that GCC's reachability analysis will remain confused in that case.)
