### PR TITLE
prohibit pointers to bit-vectors that are not byte-aligned

### LINKED ISSUE #7104: Unexpected assertion result with arrays of __CPROVER_bitvector
CBMC version: 5.65.1 (cbmc-5.65.1) 64-bit x86_64 linux
Operating system: RHEL7
Exact command line resulting in the issue:

main.c
```
struct Foo1 { __CPROVER_bitvector[1] m_array[2]; };
struct Foo8 { __CPROVER_bitvector[8] m_array[2]; };

int main(void)
{
    struct Foo1 f1;
    struct Foo8 f8;

    __CPROVER_assert(f1.m_array[1] == *(f1.m_array + 1), "");
    __CPROVER_assert(f8.m_array[1] == *(f8.m_array + 1), "");
    return 0;
}

```

```
$ ./cbmc main.c
CBMC version 5.65.1 (cbmc-5.65.1) 64-bit x86_64 linux
Parsing main.c
Converting
Type-checking main
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Runtime Symex: 0.00162542s
size of program expression: 40 steps
simple slicing removed 5 assignments
Generated 2 VCC(s), 1 remaining after simplification
Runtime Postprocess Equation: 0.000118281s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000258398s
Running propositional reduction
Post-processing
Runtime Post-process: 6.0269e-05s
Solving with MiniSAT 2.2.1 with simplifier
62 variables, 37 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.000188411s
Runtime decision procedure: 0.000598905s

** Results:
main.c function main
[main.assertion.1] line 9 assertion: FAILURE
[main.assertion.2] line 10 assertion: SUCCESS

** 1 of 2 failed (2 iterations)
VERIFICATION FAILED
```

What behaviour did you expect:
Both assertions to pass

What happened instead:
Assertion on line 9 failed.

----

Since I investigated this issue, I'll leave my analysis:

To my understanding, the issue is in the `*(f1.m_array + 1)` expression. When CBMC tries to dereference this expression, it eventually reaches `value_set_dereference.cpp:627`:

https://github.com/diffblue/cbmc/blob/f680e0fa669b248db6e103dbafed67a2d3f72807/src/pointer-analysis/value_set_dereference.cpp#L626-L628

At this point, it receives an expression to denote the member of `Foo1` that is being dereferenced.
In the good case (Foo8), it receives a nice `index`expression, while in the bad case, it receives a `byte_extract_little_endian`.

The reason for this difference, I believe, is on a semantic mismatch of the layout of an array of bitvectors.

Diving in `get_subexpression_at_offset` leads us to `pointer_offset_size.cpp:596`, where we look for the member that matches the given offset inside the struct:

https://github.com/diffblue/cbmc/blob/f680e0fa669b248db6e103dbafed67a2d3f72807/src/util/pointer_offset_size.cpp#L596-L619

This is done by iterating the members of the struct, tracking their offset and their size. Then it's possible to calculate if the offset we are looking for is inside such member. If we find it, we recurse into that member.

In the line `pointer_offset_size.cpp:603`, for the "good" case, we ask for the size (in bits) of the `__CPROVER_bitvector[8] [2]` the answer is 16 bits. That's perfect.

However, on the "bad" case, we ask for the size of `__CPROVER_bitvector[1] [2]` and it answers 2 bits.
Of course, since I'm looking for the second element, my offset is 1 byte which is beyond the 2 bits of size claimed by the array.

This code fails to find the appropriate member, and fallsback to the `byte_extract_little_endian`. And that is still wrong because it extracts the second byte in the struct, which isn't where the element is (according to the semantics above), hence the property fails.

There seems to exist a semantic mistmatch between C language and the bitvector extension.

In C, there is no way an array with two elements takes only 2 bits. Since you can take the address of each element individually, and these addresses must be different, they must be at least one byte apart.

I understand this is not pure C, so there is room for custom semantics, but as shown in the testcase, these semantics can cause very unexpected results.

I thought about a few possible ways to solve this. This problem is generally fixed by introducing paddings. For example, bitfields inside of structs will trigger the insertion of padding bits to round the next element to a byte-aligned position:

1.  Add an "element padding" attribute on the array. This would allow the usage of arrays with the current semantics in other places, but the C frontend would create them with paddings. It would require review of all places using array types though.

2. Create `__CPROVER_aligned_bitvector` types that have internal paddings to allow safe usage in C. All operations with these types would just forward to the internal `__CPROVER_bitvector` type. Then it's up to the user to choose.

3. Change the semantic of `__CPROVER_bitvector` such that that their size is always rounded up. I guess this is fine if field-sensitivity kicks in, but can be wasteful if not.

Let me know if you need any more information, or I can help with anything.

### PR DESCRIPTION
**Pull request by kroening**
This adds checks to the C front-end that prohibit taking the address of objects that cannot be addressed with byte-granularity pointers.  This includes proper Booleans (not to be confused with `_Bool`) and `__CPROVER_bitvector`-typed objects whose width is not a multiple of 8.

Fixes #7104.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [X] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/ansi-c/c_typecast.cpp [hunk 1]
```diff
@@ -765,3 +774,31 @@ void c_typecastt::do_typecast(exprt &expr, const typet &dest_type)
...
+  if(
+    type.id() == ID_unsignedbv || type.id() == ID_signedbv ||
+    type.id() == ID_bv || type.id() == ID_floatbv)
+  {
+    // The width of the bitvector must be a multiple of CHAR_BIT.
+    auto width = to_bitvector_type(type).get_width();
+    if(width % config.ansi_c.char_width != 0)
+      return std::string(
+        "bitvector must have width that is a multiple of CHAR_BIT");
+    else
```
Comment (tautschnig) [inline src/ansi-c/c_typecast.cpp]: Nit pick: braces around multi-line body

File: src/ansi-c/c_typecast.cpp [hunk 2]
```diff
@@ -765,3 +774,31 @@ void c_typecastt::do_typecast(exprt &expr, const typet &dest_type)
...
+  if(type.id() == ID_c_bit_field)
+    return std::string("cannot take address of a bit field");
+
+  if(type.id() == ID_bool)
+    return std::string("cannot take address of a proper Boolean");
+
+  if(
+    type.id() == ID_unsignedbv || type.id() == ID_signedbv ||
+    type.id() == ID_bv || type.id() == ID_floatbv)
+  {
```
Comment (tautschnig) [inline src/ansi-c/c_typecast.cpp]: Perhaps `can_cast_type<bitvector_typet>` (which has several more cases that also seem legitimate).

File: src/ansi-c/c_typecheck_expr.cpp [hunk 3]
```diff
@@ -1187,6 +1188,16 @@ void c_typecheck_baset::typecheck_expr_typecast(exprt &expr)
...
   else if(op_type.id()==ID_array)
   {
+    // This is the promotion from an array
+    // to a pointer to the first element.
+    auto error_opt = c_typecastt::check_address_can_be_taken(op_type);
+    if(error_opt.has_value())
+    {
+      error().source_location = expr.source_location();
+      error() << *error_opt << eom;
+      throw 0;
```
Comment (tautschnig) [inline src/ansi-c/c_typecheck_expr.cpp]: `throw invalid_source_file_exceptiont{*error_opt, expr.source_location()};`

File: src/ansi-c/c_typecheck_expr.cpp [hunk 4]
```diff
@@ -1710,17 +1721,12 @@ void c_typecheck_baset::typecheck_expr_address_of(exprt &expr)
...
-  }
+  auto error_opt = c_typecastt::check_address_can_be_taken(op.type());
 
-  if(op.is_boolean())
+  if(error_opt.has_value())
   {
     error().source_location = expr.source_location();
-    error() << "cannot take address of a single bit" << eom;
+    error() << *error_opt << eom;
     throw 0;
```
Comment (tautschnig) [inline src/ansi-c/c_typecheck_expr.cpp]: `throw invalid_source_file_exceptiont{*error_opt, expr.source_location()};`

**Review by tautschnig — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]
