### PR TITLE
Handle empty unions via dedicated expression

### LINKED ISSUE #6163: Invariant violation in boolbv_width.cpp
CBMC version: 5.30
Operating system: OSX
Exact command line resulting in the issue: 
Using this branch of RMC https://github.com/danielsn/rmc/tree/thread-lo
On this test: https://github.com/danielsn/rmc/blob/thread-lo/rust-tests/cbmc-reg/Static/fixme_thread_local.rs
```
╰─$ rmc --keep-temps --gen-c fixme_thread_local.rs
CBMC version 5.30.0 (cbmc-5.30.0) 64-bit x86_64 macos
Parsing /Users/dsn/ws/rmc/library/rmc/rmc_lib.c
Converting
Type-checking rmc_lib
Reading GOTO program from file
Reading: fixme_thread_local.goto
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
replacing function pointer by 1 possible targets
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Unwinding loop _RINvMs_NtNtNtCskeHm4v7Nni3_3std6thread5local4fastINtB5_3KeymE14try_initializeNvNvCs1eoHebAXHQh_18fixme_thread_local3FOO6___initEB1h_.0 iteration 1  thread 0
Unwinding loop _RINvMs_NtNtNtCskeHm4v7Nni3_3std6thread5local4fastINtB5_3KeymE14try_initializeNvNvCs1eoHebAXHQh_18fixme_thread_local3FOO6___initEB1h_.1 iteration 1  thread 0
**** WARNING: no body for function _ZN3std3sys4unix17thread_local_dtor13register_dtor17h0f484916b69ea58fE
Unwinding loop _RINvMs_NtNtNtCskeHm4v7Nni3_3std6thread5local4fastINtB5_3KeymE14try_initializeNvNvCs1eoHebAXHQh_18fixme_thread_local3FOO6___initEB1h_.2 iteration 1 file /Users/dsn/ws/rmc/library/std/src/thread/local.rs line 608 column 16 function _RINvMs_NtNtNtCskeHm4v7Nni3_3std6thread5local4fastINtB5_3KeymE14try_initializeNvNvCs1eoHebAXHQh_18fixme_thread_local3FOO6___initEB1h_ thread 0
Unwinding loop _RINvMs_NtNtNtCskeHm4v7Nni3_3std6thread5local4fastINtB5_3KeymE14try_initializeNvNvCs1eoHebAXHQh_18fixme_thread_local3FOO6___initEB1h_.3 iteration 1  thread 0
Unwinding loop _RINvMs_NtNtNtCskeHm4v7Nni3_3std6thread5local4fastINtB5_3KeymE3getNvNvCs1eoHebAXHQh_18fixme_thread_local3FOO6___initEB15_.0 iteration 1  thread 0
Unwinding loop _RINvMNtCsklTF4tl7UoN_4core6optionINtB3_6OptionRmE5ok_orNtNtNtCskeHm4v7Nni3_3std6thread5local11AccessErrorECs1eoHebAXHQh_18fixme_thread_local.0 iteration 1  thread 0
Runtime Symex: 0.0411644s
size of program expression: 826 steps
simple slicing removed 13 assignments
Generated 12 VCC(s), 12 remaining after simplification
Runtime Postprocess Equation: 7.2536e-05s
Passing problem to propositional reduction
converting SSA
warning: ignoring nil
--- begin invariant violation report ---
Invariant check failed
File: /tmp/cbmc-20210513-58586-1vd9noc/src/solvers/flattening/boolbv_width.cpp:197 function: get_entry
Condition: false
Reason: Unimplemented
Backtrace:
0   cbmc                                0x00000001015e2fda _Z15print_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 74
1   cbmc                                0x00000001015e34cb _Z13get_backtracev + 167
2   cbmc                                0x000000010164e39c _Z29invariant_violated_structuredI17invariant_failedtJRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEENS1_9enable_ifIXsr3std10is_base_ofIS0_T_EE5valueEvE4typeES9_S9_iS9_DpOT0_ + 44
3   cbmc                                0x00000001015f4d29 _Z25invariant_violated_stringRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEES7_iS7_S7_ + 9
4   cbmc                                0x000000010149281c _ZNK13boolbv_widtht9get_entryERK5typet + 3316
5   cbmc                                0x0000000101495eef _ZNK12bv_pointerst18bv_pointers_widthtclERK5typet + 143
6   cbmc                                0x000000010146d066 _ZN7boolbvt17conversion_failedERK5exprt + 64
7   cbmc                                0x000000010146db29 _ZN7boolbvt17convert_bitvectorERK5exprt + 2721
8   cbmc                                0x000000010149a881 _ZN12bv_pointerst17convert_bitvectorERK5exprt + 3407
9   cbmc                                0x000000010146ccfa _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 702
10  cbmc                                0x00000001014765f3 _ZN7boolbvt19convert_byte_updateERK17byte_update_exprt + 371
11  cbmc                                0x000000010146d708 _ZN7boolbvt17convert_bitvectorERK5exprt + 1664
12  cbmc                                0x000000010149a881 _ZN12bv_pointerst17convert_bitvectorERK5exprt + 3407
13  cbmc                                0x000000010146ccfa _ZN7boolbvt10convert_bvERK5exprtN6nonstd13optional_lite8optionalImEE + 702
14  cbmc                                0x00000001014706c8 _ZN7boolbvt27boolbv_set_equality_to_trueERK11equal_exprt + 206
15  cbmc                                0x000000010147079d _ZN7boolbvt6set_toERK5exprtb + 101
16  cbmc                                0x00000001012c6e57 _ZN22symex_target_equationt19convert_assignmentsER19decision_proceduret + 243
17  cbmc                                0x00000001012c6ae8 _ZN22symex_target_equationt26convert_without_assertionsER19decision_proceduret + 116
18  cbmc                                0x00000001012c7f55 _ZN22symex_target_equationt7convertER19decision_proceduret + 35
19  cbmc                                0x00000001011b7662 _Z29convert_symex_target_equationR22symex_target_equationtR19decision_proceduretR16message_handlert + 125
20  cbmc                                0x00000001011b8bb6 _Z24prepare_property_deciderRNSt3__113unordered_mapI8dstringt14property_infotNS_4hashIS1_EENS_8equal_toIS1_EENS_9allocatorINS_4pairIKS1_S2_EEEEEER22symex_target_equationtR28goto_symex_property_decidertR19ui_message_handlert + 223
21  cbmc                                0x00000001011beb38 _ZN25multi_path_symex_checkertclERNSt3__113unordered_mapI8dstringt14property_infotNS0_4hashIS2_EENS0_8equal_toIS2_EENS0_9allocatorINS0_4pairIKS2_S3_EEEEEE + 218
22  cbmc                                0x00000001011b6071 _ZN43all_properties_verifier_with_trace_storagetI25multi_path_symex_checkertEclEv + 55
23  cbmc                                0x00000001011aff52 _ZN19cbmc_parse_optionst4doitEv + 3560
24  cbmc                                0x00000001015f906c _ZN19parse_options_baset4mainEv + 136
25  cbmc                                0x00000001011a7d8c main + 44
26  libdyld.dylib                       0x00007fff6c521cc9 start + 1


--- end invariant violation report ---
```
What behaviour did you expect: CBMC to run on the generated file
What happened instead: The invariant violation

### PR DESCRIPTION
**Pull request by tautschnig**
GCC and Clang support empty unions, which the C standard does not
permit. We previously handled this special case by generating nil. This,
however, is not supported by the bitvector back-end. Rather than coming
up with selective handling of the otherwise unexpected nil, a proper
expression is introduced (and handled).

Fixes: #6163

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by tautschnig** [comment]
I should also revisit #5667 once this is merged.

File: src/util/std_expr.h [hunk 1]
```diff
@@ -1662,6 +1662,51 @@ inline union_exprt &to_union_expr(exprt &expr)
   return ret;
 }
 
+/// \brief Union constructor to support unions without any member (a GCC/Clang
+/// feature).
+class empty_union_exprt : public nullary_exprt
+{
+public:
+  empty_union_exprt(typet _type)
```
Comment (kroening) [inline src/util/std_expr.h]: I'd make that constructor `explicit`.

**Review by kroening — APPROVED** [review]

**Review by martin-cs — APPROVED** [review]
Yes.  I'm probably being unhelpful but what happens if you have a pointer to one of these?

**Comment by tautschnig** [comment]
> Yes. I'm probably being unhelpful but what happens if you have a pointer to one of these?

I don't think that would be a problem, as long as you never try to access any bytes in there.
