### PR TITLE
C front-end: fix the interaction between packing and alignment

### LINKED ISSUE #7596: Incorrect/inconsistent sizing in determining struct - field ordering dependent
CBMC version: 5.78.0 (from Docker image `diffblue/cbmc:5.78.0`)
Operating system: Ubuntu 20.04.5 LTS (Focal Fossa)
Exact command line resulting in the issue: `docker run --rm -v $(pwd):/DUV diffblue/cbmc:5.78.0 cbmc --64 /DUV/test.c`
What behaviour did you expect: Verification pass -- two struct having the same size.
What happened instead: Verification fail -- two structs interpreted as of size 64 and 68, respectively.

Example code:
``` c
#define PADDING_SIZE (64 - sizeof(unsigned char) - sizeof(unsigned int))

typedef struct {
  unsigned char uchar;
  unsigned int uint;
  unsigned char padding[PADDING_SIZE];
} a_t;

typedef struct {
  unsigned int uint;
  unsigned char uchar;
  unsigned char padding[PADDING_SIZE];
} b_t;

int main() {
  assert (sizeof(a_t) == sizeof(b_t));
  return 0;
}
```

### PR DESCRIPTION
**Pull request by tautschnig**
Alignment computation must consider packing set for the surrounding compound type.

Fixes: #7596

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/ansi-c/padding.cpp [hunk 1]
```diff
@@ -48,25 +50,26 @@ mp_integer alignment(const typet &type, const namespacet &ns)
...
   else if(type.id()==ID_struct || type.id()==ID_union)
   {
+    const bool packed = in_packed || type.get_bool(ID_C_packed);
     result=1;
 
     // get the max
     // (should really be the smallest common denominator)
     for(const auto &c : to_struct_union_type(type).components())
-      result = std::max(result, alignment(c.type(), ns));
+      result = std::max(result, alignment(c.type(), ns, packed));
```
Comment (kroening) [inline src/ansi-c/padding.cpp]: Does packing of an outer struct really affect the inner one?

File: src/ansi-c/padding.cpp [hunk 2]
```diff
@@ -217,7 +221,7 @@ static void add_padding_msvc(struct_typet &type, const namespacet &ns)
       // pad up to underlying type unless the struct is packed
       if(!is_packed)
       {
-        const mp_integer a = alignment(it->type(), ns);
+        const mp_integer a = alignment(it->type(), ns, is_packed);
```
Comment (kroening) [inline src/ansi-c/padding.cpp]: Maybe `false` for clarity?

File: src/ansi-c/padding.h [hunk 3]
```diff
@@ -19,7 +19,7 @@ class struct_typet;
 class typet;
 class union_typet;
 
-mp_integer alignment(const typet &type, const namespacet &);
+mp_integer alignment(const typet &type, const namespacet &, bool in_packed);
```
Comment (kroening) [inline src/ansi-c/padding.h]: I'd make the namespace the last parameter, for consistency.

File: src/ansi-c/padding.cpp (hunk 1 above)
Comment (tautschnig) [reply src/ansi-c/padding.cpp]: That's how I'd interpret GCC's docs, yes: from https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html#Common-Type-Attributes (note the second sentence): 
> This attribute, attached to a struct, union, or C++ class type definition, specifies that each of its members (other than zero-width bit-fields) is placed to minimize the memory required. This is equivalent to specifying the packed attribute on each of the members.

Comment (kroening) [reply src/ansi-c/padding.cpp]: Not sure that "nested members" count as "members" here?

Comment (kroening) [reply src/ansi-c/padding.cpp]: https://stackoverflow.com/questions/16904613/whats-the-effect-of-attribute-packed-on-nested-structs

File: src/ansi-c/padding.cpp (hunk 2 above)
Comment (tautschnig) [reply src/ansi-c/padding.cpp]: Done.

File: src/ansi-c/padding.h (hunk 3 above)
Comment (tautschnig) [reply src/ansi-c/padding.h]: Done.

File: src/ansi-c/padding.cpp (hunk 1 above)
Comment (tautschnig) [reply src/ansi-c/padding.cpp]: I've got more work to do it seems: I have expanded the regression test, and it is now failing (GCC things the static assertions are fine).

**Review by TGWDB — APPROVED** [review]

**Review by kroening — APPROVED** [review]
