### PR TITLE
SMT back-end: Extend trace value evaluation

### LINKED ISSUE #7308: Invariant check fails with `--z3` and `--json-ui`
This test is the same one in #7185, but with an extra assert:
```C
#include <assert.h>

struct Unit
{
};

int main() {
    struct Unit var_0;
    int x;
    int y = x;
    assert(0);
    assert(y == x);
    return 0;
}
```
Running it with `--z3` and `--json-ui` causes an invariant violation:
```
$ cbmc unit2.c --z3 --json-ui
[
  {
    "program": "CBMC 5.69.1 (cbmc-5.69.1)"
  },
  {
    "messageText": "CBMC version 5.69.1 (cbmc-5.69.1) 64-bit x86_64 linux",
    "messageType": "STATUS-MESSAGE"
  },
  {
    "messageText": "Parsing unit2.c",
    "messageType": "STATUS-MESSAGE"

# -- snip --

          }--- begin invariant violation report ---
Invariant check failed
File: ../src/goto-programs/json_goto_trace.cpp:121 function: convert_decl
Condition: step.full_lhs_value.is_not_nil()
Reason: full_lhs_value in assignment must not be nil
Backtrace:
cbmc(+0xa8bde0) [0x559203cd5de0]
cbmc(+0xa8c389) [0x559203cd6389]
cbmc(+0x1e7d98) [0x559203431d98]
cbmc(+0x6853c6) [0x5592038cf3c6]
cbmc(+0x33d9f2) [0x5592035879f2]
cbmc(+0x357cac) [0x5592035a1cac]
cbmc(+0x1ef124) [0x559203439124]
cbmc(+0x1ee5fa) [0x5592034385fa]
cbmc(+0x1e5e2f) [0x55920342fe2f]
cbmc(+0x1d1e39) [0x55920341be39]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f8da07cc0b3]
cbmc(+0x1e77ae) [0x5592034317ae]


--- end invariant violation report ---
Aborted (core dumped)
```
This doesn't crash if I remove either of the `--z3` or the `--json-ui` options.

CBMC version: 5.69.1
Operating system: Ubuntu 20.04
Exact command line resulting in the issue: `cbmc unit2.c --z3 --json-ui`
What behaviour did you expect: Verification fails
What happened instead: CBMC crashed

### PR DESCRIPTION
**Pull request by tautschnig**
We record the values of expressions by adding `expr == expr` as constraints in order to be able to fetch and display them in the GOTO trace (for declaration; we presently also introduce new symbols in other cases). Constructing a trace then requires the ability to evaluate all kinds of expressions to obtain the value for those expressions.

Fixes: #7308

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/solvers/smt2/smt2_conv.cpp [hunk 1]
```diff
@@ -321,16 +313,23 @@ exprt smt2_convt::get(const exprt &expr) const
...
   {
-    exprt array_copy = *array;
-    for(auto &element : array_copy.operands())
+    exprt copy = expr;
+    for(auto &op : copy.operands())
     {
-      element = get(element);
+      exprt eval_op = get(op);
+      if(eval_op.is_nil())
+        return nil_exprt{};
```
Comment (TGWDB) [inline src/solvers/smt2/smt2_conv.cpp:329]: I don't quite understand why we return nil if any operand could be nil? The old code here (e.g.) for arrays would leave the nil in place and return the larger expr.

Comment (tautschnig) [reply src/solvers/smt2/smt2_conv.cpp:329]: I'd fear that we fail to notice problems. I'm not sure returning `nil` ever is the right thing to do?

**Comment by kroening** [comment]
The question is whether the decision procedure or the user of the decision procedure ought to do the simplification.

**Review by peterschrammel — COMMENTED** [review]
> `Reason: full_lhs_value in assignment must not be nil`

How does simplification make it non-nil?

**Comment by tautschnig** [comment]
@kroening said:
> The question is whether the decision procedure or the user of the decision procedure ought to do the simplification.

I accept that the changes introducing simplification to io_args could be factored out, they were a bit of a drive-by cleanup. We already do this in other branches of `build_goto_trace`, so it just seemed like a good idea to make code simpler. Let me know if you want me to remove those from the PR.

@peterschrammel said:
>> `Reason: full_lhs_value in assignment must not be nil`

> How does simplification make it non-nil?

Would you mind elaborating for I'm not sure how this comment came about?

**Comment by peterschrammel** [comment]
> Would you mind elaborating for I'm not sure how this comment came about?

I'm referring to the [issue](https://github.com/diffblue/cbmc/issues/7308) that is supposed to fixed here. I'm not entirely sure I understand how simplification fixes it.

**Comment by tautschnig** [comment]
> > Would you mind elaborating for I'm not sure how this comment came about?
> 
> I'm referring to the [issue](https://github.com/diffblue/cbmc/issues/7308) that is supposed to fixed here. I'm not entirely sure I understand how simplification fixes it.

Ah! The issue is fixed by the changes in this PR as https://github.com/diffblue/cbmc/pull/7310/files#diff-0eb7414a51aacc433e17eec049af7ed61dd62d3ee3c4b466f991c60a861c7fccR390-R391 will now receive a non-nil value. Not a matter of simplification at all.

**Comment by tautschnig** [comment]
> The question is whether the decision procedure or the user of the decision procedure ought to do the simplification.

I have removed the simplification changes from this PR and moved them to #7323 instead.

**Review by peterschrammel — APPROVED** [review]
