### PR TITLE
Fix failed coverage in if then else with return statements

### LINKED ISSUE #7974: GOTO conversion of `return` inside `if-then-else`  generates unreachable instructions
When a `return` statement terminates a block in an `if-then-else`, GOTO conversion emits :

1. a SET_RETURN_VALUE
2. a GOTO statement to encode the `return` 
3. a GOTO statement to jump out of the if- or else-if block

As a result `--cover location` reports that the block containing the second GOTO statement is unreachable.

Since both GOTO statements have the same source location and there is nothing after the return statement, this makes it look like the return statement is both reachable and unreachable for a user looking at the C code.

Would it be possible to simplify away the second GOTO since it is purely an artifact of goto conversion and statically unreachable ?

```C
int nondet_int();

int main() {
    if (nondet_int()) {
        return -1;
    } else if (nondet_int()) {
        return -1;
    } else if (nondet_int()) {
        return -1;
    }
    return 0;
}
```

Coverage results:

```bash
** coverage results:
[main.coverage.1] file double_goto.c line 4 function main block 1 (lines double_goto.c:main:4): SATISFIED
[main.coverage.2] file double_goto.c line 5 function main block 2 (lines double_goto.c:main:5): SATISFIED
[main.coverage.3] file double_goto.c line 5 function main block 3 (lines double_goto.c:main:5): FAILED
[main.coverage.4] file double_goto.c line 6 function main block 4 (lines double_goto.c:main:6): SATISFIED
[main.coverage.5] file double_goto.c line 7 function main block 5 (lines double_goto.c:main:7): SATISFIED
[main.coverage.6] file double_goto.c line 7 function main block 6 (lines double_goto.c:main:7): FAILED
[main.coverage.7] file double_goto.c line 8 function main block 7 (lines double_goto.c:main:8): SATISFIED
[main.coverage.8] file double_goto.c line 9 function main block 8 (lines double_goto.c:main:9): SATISFIED
[main.coverage.9] file double_goto.c line 11 function main block 9 (lines double_goto.c:main:11): SATISFIED
[main.coverage.10] file double_goto.c line 12 function main block 10 (lines double_goto.c:main:12): SATISFIED

** 8 of 10 covered (80.0%)
** Used 5 iterations
```

Goto functions :

```C
main /* main */
        // 0 file double_goto.c line 4 function main
        DECL main::$tmp::return_value_nondet_int$1 : signedbv[32]
        // 1 file double_goto.c line 4 function main
        ASSIGN main::$tmp::return_value_nondet_int$1 := side_effect statement="nondet" #identifier="nondet_int" is_nondet_nullable="1"
        // 2 file double_goto.c line 4 function main
        IF ¬(main::$tmp::return_value_nondet_int$1 ≠ 0) THEN GOTO 1

/* reachable */

        // 3 file double_goto.c line 5 function main
        SET RETURN VALUE -1
        // 4 file double_goto.c line 5 function main
        GOTO 6

/* unreachable */
        // 5 file double_goto.c line 5 function main
        GOTO 5

        // 6 file double_goto.c line 6 function main
     1: DECL main::$tmp::return_value_nondet_int$0 : signedbv[32]
        // 7 file double_goto.c line 6 function main
        ASSIGN main::$tmp::return_value_nondet_int$0 := side_effect statement="nondet" #identifier="nondet_int" is_nondet_nullable="1"
        // 8 file double_goto.c line 6 function main
        IF ¬(main::$tmp::return_value_nondet_int$0 ≠ 0) THEN GOTO 2

/* reachable */
        // 9 file double_goto.c line 7 function main
        SET RETURN VALUE -1
        // 10 file double_goto.c line 7 function main
        GOTO 6

/* unreachable */
        // 11 file double_goto.c line 7 function main
        GOTO 4

        // 12 file double_goto.c line 8 function main
     2: DECL main::$tmp::return_value_nondet_int : signedbv[32]
        // 13 file double_goto.c line 8 function main
        ASSIGN main::$tmp::return_value_nondet_int := side_effect statement="nondet" #identifier="nondet_int" is_nondet_nullable="1"
        // 14 file double_goto.c line 8 function main
        IF ¬(main::$tmp::return_value_nondet_int ≠ 0) THEN GOTO 3
        // 15 file double_goto.c line 9 function main
        SET RETURN VALUE -1
        // 16 file double_goto.c line 9 function main
        GOTO 6
        // 17 no location
     3: SKIP
        // 18 no location
     4: SKIP
        // 19 no location
     5: SKIP
        // 20 file double_goto.c line 11 function main
        SET RETURN VALUE 0
        // 21 file double_goto.c line 11 function main
        DEAD main::$tmp::return_value_nondet_int$1
        // 22 file double_goto.c line 11 function main
        DEAD main::$tmp::return_value_nondet_int$0
        // 23 file double_goto.c line 11 function main
        DEAD main::$tmp::return_value_nondet_int
        // 24 file double_goto.c line 11 function main
        GOTO 6
        // 25 file double_goto.c line 12 function main
     6: END_FUNCTION


```

CBMC version: 5.94.0
Operating system: linux
Exact command line resulting in the issue: cbmc --cover locations main.c
What behaviour did you expect: all  blocks reachable
What happened instead: some dead blocks are not reachable

### PR DESCRIPTION
**Pull request by esteffin**
Fixes #7974

Avoid adding useless goto blocks in `if` statements with `return` statements.

When the parsed AST is transformed in GOTO language the `if` statements are translated in: `if (!c) goto else; then_branch; goto endif; else: else_branch; endif: nop` and `if (!c) goto endif; then_branch; endif: nop`.

This PR avoids to add the `goto endif` command and the `endif` label if the `then_branch` already ends with a `return` or a `goto` statement.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by thomasspriggs — APPROVED** [review]

**Review by TGWDB — APPROVED** [review]

**Comment by esteffin** [comment]
@kroening This PR involves some changes to a regression test of the `cprover` tool.

Can you please have a look that the changes are ok?

**Comment by kroening** [comment]
I am on the fence on this PR. It's of course true that the code after a `return` won't ever be covered. But where do we draw the line? Say why not include `__noreturn` functions? This eventually becomes the full program reachability problem, which is what the cover feature is meant to solve.

**Comment by thomasspriggs** [comment]
> I am on the fence on this PR. It's of course true that the code after a `return` won't ever be covered. But where do we draw the line? Say why not include `__noreturn` functions? This eventually becomes the full program reachability problem, which is what the cover feature is meant to solve.

@kroening I was on the fence as per my comments on https://github.com/diffblue/cbmc/issues/7974
However I have reconsidered since my initial comments, such that I am currently in favour of improving our coverage output based on avoiding *introducing* unreachable code in conversion to goto. I consider the unreachable goal to be unhelpful in this case because it does not correspond to a user statement. This is even clearer if you consider that the issue affects this variation on the input example without the brackets -

<details>
  <summary>C example</summary>
  
```C
int nondet_int();

int main() {
    if (nondet_int())
        return -1;
    else if (nondet_int())
        return -1;
    else
        return -1;
    return 0;
}
```
</details>

<details>
  <summary>coverage output</summary>
  
```
** coverage results:
[main.coverage.1] file ./no_bracket_example.c line 4 function main block 1 (lines ./no_bracket_example.c:main:4): SATISFIED
[main.coverage.2] file ./no_bracket_example.c line 5 function main block 2 (lines ./no_bracket_example.c:main:5): SATISFIED
[main.coverage.3] file ./no_bracket_example.c line 5 function main block 3 (lines ./no_bracket_example.c:main:5): FAILED
[main.coverage.4] file ./no_bracket_example.c line 6 function main block 4 (lines ./no_bracket_example.c:main:6): SATISFIED
[main.coverage.5] file ./no_bracket_example.c line 7 function main block 5 (lines ./no_bracket_example.c:main:7): SATISFIED
[main.coverage.6] file ./no_bracket_example.c line 7 function main block 6 (lines ./no_bracket_example.c:main:7): FAILED
[main.coverage.7] file ./no_bracket_example.c line 9 function main block 7 (lines ./no_bracket_example.c:main:9): SATISFIED
[main.coverage.8] file ./no_bracket_example.c line 10 function main block 8 (lines ./no_bracket_example.c:main:10): FAILED
[main.coverage.9] file ./no_bracket_example.c line 11 function main block 9 (lines ./no_bracket_example.c:main:11): SATISFIED

** 6 of 9 covered (66.7%)
```
</details>

In this example there is no closing `}` for the then/true case which is unreachable as there is no code block in the source code, just a single statement.

This output also demonstrates that we are being inconsistent with how we are defining coverage. We have the helpful result in the case that the final return is unreachable (block 8). There are unhelpful goal results stating that the end of each "then true case" code block is unreachable (blocks 3 and 6). But we are missing the equivalent "unhelpful" result for the unreachable end of the "else false case" code block. Therefore the output appears to be inconsistent from a user/source perspective.

I would agree with you that we should not be partially solving the reachability problem by performing dead code elimination as part of the coverage instrumentation for example. However the way we report coverage at the moment either requires additional manual interpretation of the coverage results or mismatched goal elimination by a post-processing tool. Either solution seems potentially error-prone to me. Therefore I think it would be beneficial if we could do better in terms of our coverage reporting, rather than deferring to solutions outside of cbmc.

With regards to drawing the line between performing a full reachability analysis and improving the coverage output - I think I would currently draw the line at "we should not introduce dead code during during conversion which does not correspond to source language statements or source language branches". For a goal to really be useful it needs to map back to the source language in a way that makes sense. The change proposed in this PR gets us closer to that ideal in my opinion. With the way coverage instrumentation currently fits into the code base fixing this issue in the conversion is about as close as we can get to avoiding performing a reachability analysis to define reachability/coverage goals. The solution would look more like a reachability analysis the later we were to do it. There may be other ways the coverage analysis could be archectected in order to avoid issues like this one. But I don't see these longer term alternatives as a reason not to merge this PR, which is an improvement from a user perspective.

To refer back to the example of `__noreturn` function calls - my reading of the C standard is that this specifier is treated more as a statement of intent than a guarantee. "The implementation should produce a diagnostic message for a function declared with a _Noreturn function specifier that appears to be capable of returning to its caller." This seems to indicate a warning rather than an error on compiling `__noreturn` functions containing return statements/reaching the end. As such I don't think we should disregard the possibility of calls to `__noreturn` functions actually returning at the stage of conversion to goto.

File: src/goto-programs/goto_convert.cpp [hunk 1]
```diff
@@ -1639,13 +1639,28 @@ void goto_convertt::generate_ifthenelse(
   dest.destructive_append(tmp_v);
   dest.destructive_append(tmp_w);
 
+  // When the `then` branch of a balanced `if` condition ends with a `return` or
+  // a `goto` statement, it is not necessary to add the `goto z` and `z:` goto
+  // elements as they are never used.
+  // This helps for example when using `--cover location` as such command are
+  // marked unreachable, but are not part of the user-provided code to analyze.
+  bool then_branch_returns = dest.instructions.rbegin()->is_goto();
+
```
Comment (tautschnig) [inline src/goto-programs/goto_convert.cpp:1648]: Nit pick: I would suggest to move this block just after `CHECK_RETURN(!tmp_w.instructions.empty());` and use `tmp_w` instead of `dest`.

**Review by tautschnig — APPROVED** [review]
I believe this is an improvement in the right place. It might not be perfect, but it does improve our code generation.
