### PR TITLE
Fix invalid assumptions and invariants in GraphML witness generation

### LINKED ISSUE #5264: Invalid assumptions and invariants in witnesses of CBMC
When looking at a [CBMC witness](https://sv-comp.sosy-lab.org/2020/results/fileByHash/c69f30b31dd3676d23cfa5c4863c82d5fd1e1068eb431f5175a4af0fd512daf1.graphml) from SV-COMP, one can see that there are several circumstances where CBMC adds invalid assumptions that violate the [rules of the witness format](https://github.com/sosy-lab/sv-witnesses) for `assumption` and `assumption.scope`.

1. Initializations of global variables are declared to be in the scope of a non-existing function `__CPROVER_initialize`:
    ```
    <edge source="4079.19" target="4082.302">
      <data key="originfile">../../sv-benchmarks/c/aws-c-common/aws_byte_buf_cat_harness.i</data>
      <data key="startline">8915</data>
      <data key="threadId">0</data>
      <data key="assumption">errors[0l].error_code = 0;</data>
      <data key="assumption.scope">__CPROVER_initialize</data>
    </edge>
    ```
    Here, `assumption.scope` should be removed.

2. There are assumptions declared for internals of extern functions like `malloc`, referencing non-existing variables:
    ```
    <edge source="2834.362" target="355.384">
      <data key="originfile">../../sv-benchmarks/c/aws-c-common/aws_byte_buf_cat_harness.i</data>
      <data key="startline">6960</data>
      <data key="threadId">0</data>
      <data key="assumption">malloc_size = 4ul;</data>
      <data key="assumption.scope">malloc</data>
    </edge>
    ```
    These should be removed.

3. There are assumptions referencing local variables that are out of scope:
    ```
    <edge source="21.389" target="2196.393">
      <data key="originfile">../../sv-benchmarks/c/aws-c-common/aws_byte_buf_cat_harness.i</data>
      <data key="startline">9136</data>
      <data key="threadId">0</data>
      <data key="assumption">buf = &amp;buffer1;</data>
      <data key="assumption.scope">aws_byte_buf_is_valid</data>
    </edge>
    ```
    The only occurrence of `buffer1` in this program is as a local variable of `aws_byte_buf_cat_harness`. This is the variable whose address ends up in `buf`, so it is understandable where this assumption comes from, but it is not possible to express this in the current witness format and the assumption should be removed.

In practice, a witness validator might ignore assumptions with invalid scopes or variable names, but especially in the last case it could easily happen that due to naming clashes between variables of different functions a syntactically valid but semantically invalid assumption is created and the witness is rejected (in the example, `aws_byte_buf_is_valid` just would need to have another parameter named `buffer1`).

The same problems exist for invariants added to correctness witnesses in the `invariant` and `invariant.scope` fields.

CBMC version: the one of SV-COMP'20, problem still occurs in CBMC 5.12
Operating system: Ubuntu 18.04 (SV-COMP environment)
Exact command line resulting in the issue: `./cbmc --graphml-witness witness.graphml --64 --propertyfile ../../sv-benchmarks/c/properties/unreach-call.prp ../../sv-benchmarks/c/aws-c-common/aws_byte_buf_cat_harness.i`

### PR DESCRIPTION
**Pull request by tautschnig**
- Remove assumptions with `__CPROVER_initialize` scope
- Filter out assumptions for internal variables of external functions
- Remove assumptions referencing out-of-scope local variables

Co-authored-by: Kiro autonomous agent

Fixes: #5264

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/goto-programs/graphml_witness.cpp [hunk 1]
```diff
@@ -274,6 +275,55 @@ static bool contains_symbol_prefix(const exprt &expr, const std::string &prefix)
...
+  if(symbol_ptr->location.is_built_in())
+    return true; // body from a built-in library source
+
+  return false;
+}
+
+/// Check if all symbols in an expression are in scope.
+/// Note: scope is determined by the prefix before the first "::". This is
+/// correct for CBMC's C front-end where locals are named "function::N::var"
+/// and function_id is "function". JBMC does not use graphml witnesses.
```
Comment (peterschrammel) [inline src/goto-programs/graphml_witness.cpp:303]: >JBMC does not use graphml witnesses.

That's incorrect, but probably doesn't matter because graphml witnesses are deprecated anyway.

**Review by peterschrammel — APPROVED** [review]
