### PR TITLE
Fix `alloca` related INVARIANT violation on Windows

### LINKED ISSUE #7869: Use of `alloca` without declaring it causes INVARIANT violation on Windows
CBMC version:
Operating system: Windows
Exact command line resulting in the issue: `goto-cl.exe alloca_issue.c`
What behaviour did you expect:
What happened instead:

The `alloca` function / intrinsic is available on Windows and is defined in `malloc.h` on this platform. See - [MS documentation website](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/alloca?view=msvc-170)

If a user program includes a usage of this function without the appropriate forward declaration or include, it causes an INVARIANT violation within the C front end. I think the appropriate behaviour in this case should be an appropriate user facing error message. Here is an example input file which triggers this behaviour -
```C
#include <assert.h>
#include <stdlib.h>

int main()
{
  int n;
  __CPROVER_assume(5 <= n && n < 10);
  int *C = alloca(n * sizeof(int));
  assert(C);
  return 0;
}
```
here is the stack trace from the INVARIANT violation -
```
--- begin invariant violation report ---
Invariant check failed
File: cbmc\src\util\pointer_expr.h:103 function: to_pointer_type
Condition: can_cast_type<pointer_typet>(type)
Reason: Precondition
Backtrace:
  0 0x7ff652ebd1d0 print_backtrace
  1 0x7ff652ebd420 get_backtrace
  2 0x7ff652a80930 invariant_violated_structured<invariant_failedt,std::basic_string<char,std::char_traits<char>,std::al
locator<char> > const &>
  3 0x7ff652a88c30 invariant_violated_string
  4 0x7ff652bc43c0 to_pointer_type
  5 0x7ff652ce8520 goto_convertt::do_alloca
  6 0x7ff652cdfbf0 goto_convertt::do_function_call_symbol
  7 0x7ff652cf0380 goto_convertt::do_function_call
  8 0x7ff652cf0fd0 goto_convertt::convert_function_call
  9 0x7ff652d15c00 goto_convertt::remove_function_call
  a 0x7ff652d125c0 goto_convertt::remove_side_effect
  b 0x7ff652d0d5c0 goto_convertt::clean_expr
  c 0x7ff652d0d5c0 goto_convertt::clean_expr
  d 0x7ff652cbbd50 goto_convertt::convert_frontend_decl
  e 0x7ff652cc2c70 goto_convertt::convert
  f 0x7ff652cbbb10 goto_convertt::convert_block
 10 0x7ff652cc2c70 goto_convertt::convert
 11 0x7ff652cbb630 goto_convertt::goto_convert_rec
 12 0x7ff652c68560 goto_convert_functionst::convert_function
 13 0x7ff652ad38d0 compilet::convert_symbols
 14 0x7ff652ad2e00 compilet::link
 15 0x7ff652ad20e0 compilet::doit
 16 0x7ff652ace1b0 ms_cl_modet::doit
 17 0x7ff652aa6130 goto_cc_modet::main
 18 0x7ff652a7d060 wmain
 19 0x7ff653089ce0 invoke_main
 1a 0x7ff653089a90 __scrt_common_main_seh
 1b 0x7ff653089a70 __scrt_common_main
 1c 0x7ff653089da0 wmainCRTStartup
 1d 0x7ffa158c7600 BaseThreadInitThunk
 1e 0x7ffa160026d0 RtlUserThreadStart
```

### PR DESCRIPTION
**Pull request by thomasspriggs**
This PR fixes issue https://github.com/diffblue/cbmc/issues/7869 with `alloca` on Windows.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by NlightNFotis — APPROVED** [review]
From what I've seen so far, the changes are LGTM to me.

I *think* the parsing errors the regression tests fail with is because `size_t` needs `stddef.h` to be included in order to be defined in C.

**Review by TGWDB — APPROVED** [review]

File: regression/cbmc-library/alloca_declaration/missing_parameters.c [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#include <assert.h>
+#include <stddef.h>
+
+void *alloca();
+
+int main()
+{
+  int n;
+  __CPROVER_assume(5 <= n && n < 10);
+  int *C = alloca();
```
Comment (peterschrammel) [inline regression/cbmc-library/alloca_declaration/missing_parameters.c]: ⛏️⛏️ capital C looks a bit unusual.

**Review by peterschrammel — APPROVED** [review]

File: regression/cbmc-library/alloca_declaration/missing_parameters.c (hunk 1 above)
Comment (thomasspriggs) [reply regression/cbmc-library/alloca_declaration/missing_parameters.c]: It is indeed a little unusual. This was copy and pasted from this shadow memory test here - https://github.com/diffblue/cbmc/blame/2daecc3bf6c079f7a2eda826bf00e1f44186489d/regression/cbmc-shadow-memory/nondet-size-arrays1/main.c#L85 :grin: 

I'll fix the capitalisation in my new tests before I merge.
