### PR TITLE
Fix value-set make_member function

### LINKED ISSUE #3569: value_sett::make_member is unsound wrt struct casts
Faced with an expression like `((struct X)some_struct_y).a`, value-set's `make_member` function will reduce that unsoundly to `some_struct_y.a`, here: https://github.com/diffblue/cbmc/blob/develop/src/pointer-analysis/value_set.cpp#L1654

Clearly that only works when the two structs happen to have the same layout and names. 

Expressions like that are hard to get from C, but `value_set_dereferencet` will produce them when it different struct types are aliased.

#3562 may offer a solution, by soundly simplifying member-of-cast-of-struct-typed-expression when possible.

### PR DESCRIPTION
**Pull request by smowton**
Fixes #3569; ~depends on #3562, which is the first commit in this PR.~

Previously `value_sett` would simplify ((struct A)x).y into x.y regardless of whether the two structures both have a member y, or whether it is colocated in the two types. Improve the simplifier slightly to tackle this case, then use it rather than implement custom logic in `value_sett`.

### CODE REVIEW

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 142cafe4b5c642011a639a63bf2d025df14cab35).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/94978728

File: src/pointer-analysis/value_set.cpp [hunk 1]
```diff
@@ -1630,37 +1630,10 @@ exprt value_sett::make_member(
...
-
-  // give up
   const typet &subtype = struct_union_type.component_type(component_name);
-  member_exprt member_expr(src, component_name, subtype);
+  exprt member_expr = member_exprt(src, component_name, subtype);
+
+  simplify(member_expr, ns);
 
-  return std::move(member_expr);
+  return member_expr;
```
Comment (tautschnig) [inline src/pointer-analysis/value_set.cpp:1638]: I believe this should stay as `return std::move(member_expr);`

**Review by tautschnig — APPROVED** [review]

File: src/pointer-analysis/value_set.cpp (hunk 1 above)
Comment (smowton) [reply src/pointer-analysis/value_set.cpp:1638]: Not so! It's type now matches the return type, so I leave it out and enable RVO. I hope a forthcoming version of C++ renders this distinction unnecessary...

Comment (tautschnig) [reply src/pointer-analysis/value_set.cpp:1638]: Oops, sorry, I ignored that you had used `exprt member_expr ...`.

**Review by allredj — COMMENTED** [review]
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 8d88c9776d3cb838ca1f209417f9c26bc9a09272).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/94987938

**Review by peterschrammel — APPROVED** [review]
