### PR TITLE
Concurrency: treat updates to an unknown field as atomic

### LINKED ISSUE #123: bug in concurrency encoding for arrays and structs
regression tests coming...

### PR DESCRIPTION
**Pull request by tautschnig**
Writing to an object that is composed of multiple fields is generally
treated in a field-sensitive (and thus: single-field) manner, which had
fixed several issues in handling shared arrays or structs. When the
specific field being updated cannot be determined during symbolic
execution (as is the case with non-const indices into arrays), we update
all fields that make up the full object. Such a full-object update must
then be treated as an atomic operation to avoid losing intermittent
writes performed by other threads.

Fixes: #123

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Review by TGWDB — APPROVED** [review]

File: src/goto-symex/goto_symex.cpp [hunk 1]
```diff
@@ -114,9 +114,27 @@ void goto_symext::symex_assign(
         return;
     }
 
+    // We may end up reading (and writing) all components of an object composed
+    // of multiple fields. In such cases, we must do so atomically to avoid
+    // overwriting components modified by another thread. Note that this also
+    // implies multiple shared reads on the rhs being treated as atomic.
```
Comment (martin-cs) [inline src/goto-symex/goto_symex.cpp:123]: Thanks for the comment that makes this clear but ... I am a little concerned about this because now
`struct s = t;` and

```
struct s;
s.x = t.x;
s.y = t.y;
```

can have different behaviour.  I guess there is a very valid question about what the `atomic` actions in the CPROVER concurrency model are.

Comment (tautschnig) [reply src/goto-symex/goto_symex.cpp:123]: Although this case shouldn't arise for structs and mainly affects arrays: you are absolutely right that this is questionable either way. Without this patch, we'll have spurious results (as documented in the regression test). With this patch, we may miss some behaviour, depending on what exactly we otherwise consider to be atomic.

**Review by peterschrammel — APPROVED** [review]
