### PR TITLE
Flexible array members: make type checking aware and fix bounds checking

### LINKED ISSUE #6787: CBMC error if variable of type struct with flexible array member is forward declared and initialized
CBMC version: cbmc-5.54.0-13-gf3e4096300
Operating system: Linux x86_64
Exact command line resulting in the issue: cbmc fam.c
What behaviour did you expect: termination with message VERIFICATION SUCCESSFUL and exit status 0
What happened instead: termination with message CONVERSION ERROR and exit status 6

The error occurs in the following scenario:
1. There is a struct St with a flexible array member
2. A global variable with type St is both forward declared and initialized

The test case [fam.c.txt](https://github.com/diffblue/cbmc/files/8440175/fam.c.txt)  is attached.
The output is in file [cbmc.log](https://github.com/diffblue/cbmc/files/8440176/cbmc.log).

The problem was introduced by the following commit:
commit b16c7d7cd4
Author: Michael Tautschnig <tautschn@amazon.com>
Date:   Fri Feb 11 13:17:17 2022 +0000

Reverting commit b16c7d7cd4 on top of commit f3e4096300 fixes the error, but I did not check if it causes other problems.

### PR DESCRIPTION
**Pull request by tautschnig**
Type checking must be ready to handle type changes between declaration
and definition, which b16c7d7cd4 introduced. Also, bounds checking must
not use `size_of_expr` with these as 24eba850 rightly introduced a
distinction between "sizeof" and the actual object size as mandated by
the C standard.

Fixes: #6787

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/ansi-c/c_typecheck_base.cpp [hunk 1]
```diff
@@ -262,6 +262,41 @@ void c_typecheck_baset::typecheck_redefinition_type(
   }
 }
 
+static bool is_instantiation_of_flexbile_array(
```
Comment (NlightNFotis) [inline src/ansi-c/c_typecheck_base.cpp]: This has a typo in the definition of the function (`flexbile`).

Can this get fixed before any merge of the PR?

(The typo is going to make the function less discoverable, me thinks)

Comment (tautschnig) [reply src/ansi-c/c_typecheck_base.cpp]: Thank you for such careful proof reading! This is now fixed.

**Review by peterschrammel — APPROVED** [review]

**Review by kroening — APPROVED** [review]
