### PR TITLE
Fix errors emitted by C++2a compiler

### LINKED ISSUE #1972: Fatal warnings for C++2a / Clang 6.0
Dumping various errors that happen when trying to build cprover with Clang 6.0, which has experimental support for C++2a and gives off many new warnings.

```
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/ext/new_allocator.h:140:22: error: destructor called on non-final 'java_bytecode_parse_treet::methodt' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
        destroy(_Up* __p) { __p->~_Up(); }
                            ^
```
```
cbmc/src/pointer-analysis/value_set_fi.cpp:744:9: error: parentheses were disambiguated as redundant parentheses around declaration of variable named 'it' [-Werror,-Wvexing-parse]
        forall_objects(it, omt.read())
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
cbmc/src/pointer-analysis/value_set_fivr.cpp:857:9: error: parentheses were disambiguated as redundant parentheses around declaration of variable named 'it' [-Werror,-Wvexing-parse]
        forall_objects(it, omt.read())
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
cbmc/src/cpp/cpp_typecheck_resolve.cpp:591:34: error: unused variable 'next'
[-Werror,-Wunused-variable]
  resolve_identifierst::iterator next;
                                   ^
```

### PR DESCRIPTION
**Pull request by karkhaz**
This commit fixes #1972, in particular fixing these three classes of
error that occurred over various files in the codebase:
```
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/ext/new_allocator.h:140:22: error: destructor called on non-final 'java_bytecode_parse_treet::methodt' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
        destroy(_Up* __p) { __p->~_Up(); }
                            ^

cbmc/src/pointer-analysis/value_set_fivr.cpp:857:9: error: parentheses were disambiguated as redundant parentheses around declaration of variable named 'it' [-Werror,-Wvexing-parse]
        forall_objects(it, omt.read())
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cbmc/src/cpp/cpp_typecheck_resolve.cpp:591:34: error: unused variable 'next'
[-Werror,-Wunused-variable]
  resolve_identifierst::iterator next;
                                   ^
```
These warnings are emitted when building with Clang 6.0 with the default
flags. As of this commit, one warning remains, which can be suppressed
by building with the flag -Wno-c++2a-compat until we have a proper fix.

### CODE REVIEW

**Comment by karkhaz** [comment]
Sorry, here's a bit more context for the vexing-parse issue:
```
cbmc/src/pointer-analysis/value_set_fi.cpp:744:9: error: parentheses were disambiguated as redundant parentheses around declaration of variable named 'it' [-Werror,-Wvexing-parse]
        forall_objects(it, omt.read())
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cbmc/src/pointer-analysis/value_set_fi.cpp:36:37: note: expanded from macro 'forall_objects'
  for(object_map_dt::const_iterator (it) = (map).begin(); \
                                    ^~~~
cbmc/src/pointer-analysis/value_set_fi.cpp:744:9: note: add enclosing parentheses to perform a function-style cast
```
The macro had parentheses around all occurrences of the argument `it`. I've removed some but not all of the parentheses.

I'd also like to draw attention to #1974, which is not fixed by this patch, I'm hoping somebody will have some idea on how to fix it. If this patch looks okay, could we please merge it in fairly quickly?

**Comment by tautschnig** [comment]
Could you please add 'Fixes: #1972' to the commit message so that #1972 will be auto-closed upon merge?

File: src/pointer-analysis/value_set_fi.cpp [hunk 1]
```diff
@@ -33,13 +33,13 @@ hash_numbering<irep_idt, irep_id_hash> value_set_fit::function_numbering;
 static const char *alloc_adapter_prefix="alloc_adaptor::";
 
 #define forall_objects(it, map) \
-  for(object_map_dt::const_iterator (it) = (map).begin(); \
-  (it)!=(map).end(); \
+  for(object_map_dt::const_iterator it = (map).begin(); \
+  it!=(map).end(); \
   (it)++)
```
Comment (tautschnig) [inline src/pointer-analysis/value_set_fi.cpp:38]: I think this is a good reason to get rid of those macros (just the ones here, not all `forall_*`/`Forall_*`). The use of `auto` or ranged-for loop make them unnecessary.

Comment (karkhaz) [reply src/pointer-analysis/value_set_fi.cpp:38]: Not entirely, see e.g. `pointer-analysis/value_set_fivr.cpp:202`:
```
      object_map_dt::const_iterator next(o_it);
      next++;

      if(next!=object_map.read().end())
      {
        out << "\n      ";
      }
```
I cannot construct an iterator from the value ranged over by `for(auto const &...)`, do you have a suggestion on how to deal with this case?

**Comment by karkhaz** [comment]
@tautschnig The commit message already contains the string "fixes #1972" which also auto-closes the issue, do you prefer it to be capitalized with a colon?

**Comment by tautschnig** [comment]
> [...] which also auto-closes the issue, do you prefer it to be capitalized with a colon?

Ah, that's fine then, wasn't aware of the level of smartness that GitHub uses.

File: src/pointer-analysis/value_set_fi.cpp (hunk 1 above)
Comment (tautschnig) [reply src/pointer-analysis/value_set_fi.cpp:38]: But using `for(auto o_it = bla.begin(); o_it != bla.end(); ++o_it)` should still work, shouldn't it?

Comment (smowton) [reply src/pointer-analysis/value_set_fi.cpp:38]: The same discussion has gone around a few times here -- our conclusion was "keep them, but only for cases where you need an explicit iterator and so a for-each loop won't do the trick"

**Review by smowton — APPROVED** [review]

File: src/pointer-analysis/value_set_fi.cpp (hunk 1 above)
Comment (karkhaz) [reply src/pointer-analysis/value_set_fi.cpp:38]: I think your reviews are conflicting: I can use a ranged-for loop when I can, but where I cannot, shall I keep the macro (without the parentheses) or write the loop header explicitly with `auto`?

Comment (tautschnig) [reply src/pointer-analysis/value_set_fi.cpp:38]: I'm in favour of removing this macro (because it's broken).

**Review by kroening — APPROVED** [review]

File: src/pointer-analysis/value_set_fi.cpp (hunk 1 above)
Comment (kroening) [reply src/pointer-analysis/value_set_fi.cpp:38]: The macros are pre-ranged-for, and should likely disappear.
