### PR TITLE
Handle bool expressions in implicit_typecast_arithmetic

### LINKED ISSUE #5103: goto-cc crashes on softfloat code using __int128
CBMC version: gcc (goto-cc 5.12 (crest.merged-48-gabe78fc77-dirty)) 7.4.0
Operating system: 4.15.0-45-generic x86_64 GNU/Linux
Exact command line resulting in the issue: goto-cc sf.c
What behaviour did you expect: no crash
What happened instead: invariant failure

The following is a reduced version of the softfloat code causing the crash:
file sf.c:
```
void softfloat_mul128To256M(unsigned a)
{
  unsigned __int128 z;
  z = (unsigned __int128) a;
  z += (a < 1);
}
```
command: `goto-cc sf.c`

output:
```
--- begin invariant violation report ---
Invariant check failed
File: ../util/std_types.h:1091 function: to_bitvector_type
Condition: can_cast_type<bitvector_typet>(type)
Reason: Precondition
...
```

### PR DESCRIPTION
**Pull request by tautschnig**
We use Booleans instead of int as type of binary predicates. This must
not preclude mixing binary predicates with bitvector-typed expressions.

Fixes: #5103

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/ansi-c/c_typecast.cpp [hunk 1]
```diff
@@ -619,8 +619,10 @@ void c_typecastt::implicit_typecast_arithmetic(
   if(max_type==LARGE_SIGNED_INT || max_type==LARGE_UNSIGNED_INT)
   {
     // get the biggest width of both
-    std::size_t width1 = to_bitvector_type(type1).get_width();
-    std::size_t width2 = to_bitvector_type(type2).get_width();
+    std::size_t width1 =
```
Comment (kroening) [inline src/ansi-c/c_typecast.cpp]: Would it make sense to use c_type1 and c_type2 instead of type1 and type2?

Comment (martin-cs) [reply src/ansi-c/c_typecast.cpp]: Agreed; this should be post-promotion.

**Review by martin-cs — COMMENTED** [review]
I think @kroening 's suggestion is correct.

File: src/ansi-c/c_typecast.cpp (hunk 1 above)
Comment (tautschnig) [reply src/ansi-c/c_typecast.cpp]: But then we'd need new facilities to turn a `c_typet` into a `typet`. It's kind-of done by c_typecastt::implicit_typecast_arithmetic, but that doesn't do anything about a `LARGE_SIGNED_INT` (or `LARGE_UNSIGNED_INT`).

Comment (tautschnig) [reply src/ansi-c/c_typecast.cpp]: I've now implemented this without a need for `to_bitvector_type` at all. Maybe I'm missing something? The new implementation seems almost too simple.

**Review by chris-ryder — APPROVED** [review]
Yeah, that does seem rather simple :-) but I can't at the moment see why it'd need to be more complex 🤷
