### PR TITLE
Function pointer restrictions: support labels in JSON input

### LINKED ISSUE #6609: Label-based function pointer restrictions fail for JSON file
I'm attempting to use the new label-based function pointer restrictions added here (CC @tautschnig): https://github.com/diffblue/cbmc/pull/6508

That PR adds a test case for the command line based restrictions. I am trying to run the same case ([regression/goto-instrument/restrict-function-pointer-by-label/test.c](https://github.com/diffblue/cbmc/pull/6508/files#diff-1928981317cb1399764c5e5ff974a2d0a1a995d3c4c874fd1d23775513ad2945)) with `--function-pointer-restrictions-file` and a JSON file instead of `--restrict-function-pointer`.

Here is the file:
```
{
    "use_f.labelled_call":[
       "f"
    ]
}
```

This fails with:

```
goto-instrument --function-pointer-restrictions-file restriction.json a.out b.out
Reading GOTO program from 'a.out'
Invalid restriction
Reason: use_f.labelled_call not found in the symbol table
```

The same restriction passed on the command line works as expected:
```
goto-instrument --restrict-function-pointer use_f.labelled_call/f a.out b.out
Reading GOTO program from 'a.out'
file test.c line 9 function use_f: replacing function pointer by 1 possible targets
Writing GOTO program to 'b.out'
```

CBMC version: 5.49.0 (cbmc-5.49.0)
Operating system: macOS 11.5.2
Exact command line resulting in the issue: 
```
goto-instrument --function-pointer-restrictions-file restriction.json a.out b.out
```
What behaviour did you expect:

The same behavior with JSON as the command line, for `f` to be passed as a restriction.

What happened instead:

Failure to find symbol.

### PR DESCRIPTION
**Pull request by tautschnig**
This is a follow-up fix to 771a153b2187b08, which added support for
labels as function-pointer identifiers. That commit, however, failed to
consider JSON input, and instead only resulted in support for
command-line specified restrictions.

Fixes: #6609

Please review commit-by-commit.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/goto-programs/restrict_function_pointers.cpp [hunk 1]
```diff
@@ -291,6 +291,62 @@ function_pointer_restrictionst::parse_function_pointer_restrictions_from_file(
   return merged_restrictions;
 }
 
+static std::string resolve_pointer_name(
```
Comment (chrisr-diffblue) [inline src/goto-programs/restrict_function_pointers.cpp:305]: A comment on the intended purpose/use-case for this new function might have been nice, but I also appreciate all you've done here is lift existing code out into a function, so I'm not going to hold it against you if you don't want/have time to add commentary. :-)

File: src/goto-programs/restrict_function_pointers.cpp [hunk 2]
```diff
@@ -523,7 +526,9 @@ function_pointer_restrictionst::from_json(const jsont &json)
 
   for(auto const &restriction : to_json_object(json))
   {
-    restrictions.emplace(irep_idt{restriction.first}, [&] {
+    std::string pointer_name =
+      resolve_pointer_name(restriction.first, goto_model);
```
Comment (chrisr-diffblue) [inline src/goto-programs/restrict_function_pointers.cpp:539]: Is there a test case that failed before this was added?

File: src/goto-instrument/goto_instrument_parse_options.cpp [hunk 3]
```diff
@@ -1029,12 +1029,7 @@ void goto_instrument_parse_optionst::instrument_goto_program()
     {
       label_function_pointer_call_sites(goto_model);
 
-      const auto function_pointer_restrictions =
-        function_pointer_restrictionst::from_options(
-          options, goto_model, log.get_message_handler());
-
-      restrict_function_pointers(
-        ui_message_handler, goto_model, function_pointer_restrictions);
+      restrict_function_pointers(ui_message_handler, goto_model, options);
```
Comment (chrisr-diffblue) [inline src/goto-instrument/goto_instrument_parse_options.cpp:1032]: Nice :-)

**Review by chrisr-diffblue — APPROVED** [review]
Looks OK to me, with bonus points if there was a test case demonstrating the fix (my apologies if I missed one...), and double bonus points if there was a little extra comments - but nothing blocking.

File: src/goto-programs/restrict_function_pointers.cpp (hunk 2 above)
Comment (tautschnig) [reply src/goto-programs/restrict_function_pointers.cpp:539]: It was not you who missed something - I had failed to do `git add`! Test is now included.

File: src/goto-programs/restrict_function_pointers.cpp (hunk 1 above)
Comment (tautschnig) [reply src/goto-programs/restrict_function_pointers.cpp:305]: Fair point, I've now added such a comment! Thank you for holding me to that bar.

File: src/goto-programs/restrict_function_pointers.cpp [hunk 4]
```diff
@@ -291,6 +298,66 @@ function_pointer_restrictionst::parse_function_pointer_restrictions_from_file(
   return merged_restrictions;
 }
 
+/// Parse \p candidate to distinguish whether it refers to a function pointer
+/// symbol directly (as produced by \ref label_function_pointer_call_sites), or
+/// a source location via its statement label. In the latter case, resolve the
+/// name to the underlying function pointer symbol.
```
Comment (chrisr-diffblue) [inline src/goto-programs/restrict_function_pointers.cpp:304]: Brilliant, thanks :-)

**Review by chrisr-diffblue — APPROVED** [review]
Thanks for the test case, and the extra commentary. Re-asserting my approval after those additions.

**Comment by tedinski** [comment]
I can confirm this solves the problem we had using restrictions files with Kani (formerly RMC).

**Review by NlightNFotis — APPROVED** [review]
LGTM

**Review by peterschrammel — APPROVED** [review]
