### PR TITLE
Value-set based dereferencing: fix simplified handling of *(p + i)

### LINKED ISSUE #8570: `__CPROVER_forall` fails when dealing with flattening of nested structure
I'm observing unexpected behaviour when trying to use `__CPROVER_forall` to access the fields of a nested array structure when cast as a flat array of cells. cc @tautschnig @remi-delmas-3000 

Minimal example:
```c
/* instructions

foo:
	goto-cc harness.c --function foo_harness -o a.out
	goto-instrument --dfcc foo_harness --enforce-contract foo a.out b.out
	cbmc b.out --bitwuzla
*/

#include <stdint.h>

typedef struct __attribute__((packed)) {
    int data[2];
} arr;

typedef struct __attribute__((packed)) {
    arr vec[2];
} arrvec;

void foo(arrvec *x)
  __CPROVER_requires(__CPROVER_is_fresh(x, sizeof(arrvec)))
  __CPROVER_requires(x->vec[1].data[0] < 42)
{
    // OK:
    __CPROVER_assert(((int*)x)[2] < 42, "");
    // NOT OK:
    __CPROVER_assert(__CPROVER_forall {unsigned k; k == 2 ==> ((int*)x)[k] < 42}, "");
    // OK:
    __CPROVER_assert(__CPROVER_forall {unsigned k; k == 2 ==> ((int (*)[2])x)[k/2][k % 2] < 42}, "");
}

void foo_harness(void) {
    arr *x;
    foo(x);
}

```

### PR DESCRIPTION
**Pull request by tautschnig**
Value-set based dereferencing must not take an access path through an object that precludes a subsequent index expression from accessing a different part of the object. Such a situation can arise when the value set has a known (constant) offset for the pointer that would identify one particular element in an array (within that object). The code using value-set based dereferencing, however, may be trying to resolve a subexpression of an index expression, where said index expression would lead to a different element that may itself be part of a different array within the same overall object.

Fixes: #8570

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

**Comment by remi-delmas-3000** [comment]
The commit adds a new argument `recurse_into_arrays` to the `get_subexpression_at_offset` to force fallback to using byte-extracts but I could not really understand what condition triggers the fallback ? Is the idea to try to resolve a lookup expression as a cell/field access if enough info is known about the index and default to a flat/unstructured by-extract otherwise ?

File: src/pointer-analysis/value_set_dereference.cpp [hunk 1]
```diff
@@ -643,11 +643,12 @@ value_set_dereferencet::valuet value_set_dereferencet::build_reference_to(
...
-    // try to build a member/index expression - do not use byte_extract
+    // Try to build a member/index expression instead of using byte_extract;
+    // don't recurse into aggregate types as the caller's expression may be
+    // within an index expression, i.e., a further offset beyond o.offset() may
+    // get added on to it.
     auto subexpr = get_subexpression_at_offset(
-      root_object, o.offset(), dereference_type, ns);
-    if(subexpr.has_value())
-      simplify(subexpr.value(), ns);
+      root_object, o.offset(), dereference_type, false, ns);
```
Comment (remi-delmas-3000) [inline src/pointer-analysis/value_set_dereference.cpp]: Can you summarize what conditions hold when reaching this line  (i.e. what forces flipping `recurse_into_arrays` to false ?)

Comment (remi-delmas-3000) [reply src/pointer-analysis/value_set_dereference.cpp]: From the comment right above it rather seems like if recurse_into_arrays is false then you try to build a field access expression, but when it is true you try to build a byte-extract that can hit the array anywhere ?

Comment (tautschnig) [reply src/pointer-analysis/value_set_dereference.cpp]: Thank you for asking all those questions, they just highlighted that the initial change was a bit dubious. Now much simpler and clearer.

**Comment by tautschnig** [comment]
@kroening Reworked as discussed.

**Review by kroening — APPROVED** [review]

**Review by peterschrammel — APPROVED** [review]
