### PR TITLE
[smt2_convt] Fix invalid and NULL pointer handling

### LINKED ISSUE #6022: Crash during SMT translation of `NULL` pointers
**CBMC version:** 99f1a2e

**Operating system:** Mac OS 10.15.7

**Test case:**

```c
#include <string.h>

void main()
{
    char *data = NULL;
    memset(data, 0, 8);
    memset(data, 0, 8);
}
```

**Exact command line resulting in the issue:**

```
$ cbmc --z3 test.c
```

**What behaviour did you expect:**

CBMC would report a verification failure.

**What happened instead:**

CBMC crashed during SMT translation:

<details>
<summary>invariant violation report</summary>

```
--- begin invariant violation report ---
Invariant check failed
File: smt2/smt2_conv.cpp:4750 function: convert_type
Condition: Precondition
Reason: false
Backtrace:
0   cbmc                                0x0000000102f6ea7a _Z15print_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 74
1   cbmc                                0x0000000102f6f002 _Z13get_backtracev + 210
2   cbmc                                0x0000000102f94660 _Z29invariant_violated_structuredI34invariant_with_diagnostics_failedtJRNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_EENS1_9enable_ifIXsr3std10is_base_ofI17invariant_failedtT_EE5valueEvE4typeERKS7_SF_iSF_DpOT0_ + 48
3   cbmc                                0x0000000102f9ab14 _Z24report_invariant_failureIJNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEEEvRKS6_S8_iS6_S6_DpOT_ + 68
4   cbmc                                0x0000000102f0d78b _ZN10smt2_convt12convert_typeERK5typet + 3067
5   cbmc                                0x0000000102f14db0 _ZN10smt2_convt12find_symbolsERK5exprt + 3808
6   cbmc                                0x0000000102effa3f _ZN10smt2_convt24prepare_for_convert_exprERK5exprt + 47
7   cbmc                                0x0000000102f133bb _ZN10smt2_convt6set_toERK5exprtb + 763
8   cbmc                                0x0000000102cecb25 _ZN22symex_target_equationt19convert_assignmentsER19decision_proceduret + 261
9   cbmc                                0x0000000102cec785 _ZN22symex_target_equationt26convert_without_assertionsER19decision_proceduret + 117
10  cbmc                                0x0000000102cedf33 _ZN22symex_target_equationt7convertER19decision_proceduret + 35
11  cbmc                                0x0000000102b8c316 _Z29convert_symex_target_equationR22symex_target_equationtR19decision_proceduretR16message_handlert + 342
12  cbmc                                0x0000000102b8e229 _Z24prepare_property_deciderRNSt3__113unordered_mapI8dstringt14property_infotNS_4hashIS1_EENS_8equal_toIS1_EENS_9allocatorINS_4pairIKS1_S2_EEEEEER22symex_target_equationtR28goto_symex_property_decidertR19ui_message_handlert + 441
13  cbmc                                0x0000000102b96007 _ZN25multi_path_symex_checkertclERNSt3__113unordered_mapI8dstringt14property_infotNS0_4hashIS2_EENS0_8equal_toIS2_EENS0_9allocatorINS0_4pairIKS2_S3_EEEEEE + 247
14  cbmc                                0x0000000103017ad3 _ZN43all_properties_verifier_with_trace_storagetI25multi_path_symex_checkertEclEv + 51
15  cbmc                                0x000000010300f879 _ZN19cbmc_parse_optionst4doitEv + 4409
16  cbmc                                0x0000000102f89538 _ZN19parse_options_baset4mainEv + 136
17  cbmc                                0x000000010300ac38 main + 40
18  libdyld.dylib                       0x00007fff6a4becc9 start + 1

Diagnostics: 
<< EXTRA DIAGNOSTICS >>
unsupported type: empty
<< END EXTRA DIAGNOSTICS >>

--- end invariant violation report ---
```

</details>

**Additional information:**

The variable need not be `NULL` explicitly, but if it could be set to `NULL` in any branch, it still leads to a crash:

```c
// crash
#include <string.h>

void main()
{
    char *data = nondet() ? NULL : malloc(8);
    memset(data, 0, 8);
    memset(data, 0, 8);
}
```

But the following program (where `data` cannot be `NULL`) does not lead to a crash during translation:

```c
// no crash
#include <stdlib.h>
#include <string.h>

void main()
{
    char *data = nondet() ? malloc(16) : malloc(8);
    memset(data, 0, 8);
    memset(data, 0, 8);
}
```

Also, a single `memset` invocation does not lead to a crash and works as expected:

```c
// no crash
#include <string.h>

void main()
{
    char *data = NULL;
    memset(data, 0, 8);
}
```

### PR DESCRIPTION
**Pull request by SaswatPadhi**
Fixes #6022.

Several SMT2 conversion functions used to crash on `NULL` pointers and other kinds of invalid pointers. This change fixes the handling of NULL pointers at several locations.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- NA ~~Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.~~
- NA ~~The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/~~
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- NA ~~My commit message includes data points confirming performance improvements (if claimed).~~
- [x] My PR is restricted to a single feature or bugfix.
- NA ~~White-space or formatting changes outside the feature-related changed lines are in commits of their own.~~

### CODE REVIEW

File: regression/cbmc/memset_null_02/main.c [hunk 1]
```diff
@@ -0,0 +1,8 @@
+#include <string.h>
```
Comment (tautschnig) [inline regression/cbmc/memset_null_02/main.c]: Do we actually need all these tests, or would one of them do the trick? Asking differently: does some variation of the fix make one of them, but not all of them fail/pass?

File: src/solvers/smt2/smt2_conv.cpp [hunk 2]
```diff
@@ -3163,7 +3163,13 @@ void smt2_convt::convert_plus(const plus_exprt &expr)
...
 
       const auto element_size = pointer_offset_size(expr.type().subtype(), ns);
-      CHECK_RETURN(element_size.has_value() && *element_size >= 1);
+      if(!element_size.has_value() || *element_size == 0)
+      {
+        // we are adding an offset to a NULL pointer with "empty" type
+        // so ignore the NULL and simply convert the offset
+        convert_expr(i);
+        return;
+      }
```
Comment (tautschnig) [inline src/solvers/smt2/smt2_conv.cpp]: I'd do as is done in `bv_pointers.cpp`: even before calling `pointer_offset_size` test for `expr.type().subtype().id() == ID_emtpy` and set `element_size` to `1` in that case.

File: src/solvers/smt2/smt2_conv.cpp [hunk 3]
```diff
@@ -4248,6 +4254,12 @@ void smt2_convt::set_to(const exprt &expr, bool value)
         CHECK_RETURN(id.type.is_nil());
 
         id.type=equal_expr.lhs().type();
+        if(id.type.id() == ID_empty)
+        {
+          // ignore converting invalid pointers with empty type
+          return;
+        }
```
Comment (tautschnig) [inline src/solvers/smt2/smt2_conv.cpp]: Two comments here:
1) I think your commit does fix two different problems, and those should be covered by two separate commits (with each of them having their particular set of tests).
2) I'd test for `equal_expr.lhs().type().id() == ID_empty` right after line 4244, there is no need for going through several branches before ending up in this case.

File: src/solvers/smt2/smt2_conv.cpp (hunk 2 above)
Comment (SaswatPadhi) [reply src/solvers/smt2/smt2_conv.cpp]: Fixed.

File: regression/cbmc/memset_null_02/main.c (hunk 1 above)
Comment (SaswatPadhi) [reply regression/cbmc/memset_null_02/main.c]: I removed `memset_null_01` since it's subsumed (during symex) by `memset_null_02`, but the other test was necessary and now I have split the tests into two different commits, as per your suggestion.

File: src/solvers/smt2/smt2_conv.cpp (hunk 3 above)
Comment (SaswatPadhi) [reply src/solvers/smt2/smt2_conv.cpp]: Thanks, fixed both as per your suggestions.

File: src/solvers/smt2/smt2_conv.cpp [hunk 4]
```diff
@@ -4247,6 +4247,11 @@ void smt2_convt::set_to(const exprt &expr, bool value)
   if(expr.id() == ID_equal && value)
   {
     const equal_exprt &equal_expr=to_equal_expr(expr);
+    if(equal_expr.lhs().type().id() == ID_empty)
+    {
+      // ignore equality checking on pointers with empty type
```
Comment (tautschnig) [inline src/solvers/smt2/smt2_conv.cpp]: This comment isn't accurate: I'd suggest "ignore equality checking over expressions with empty (void) type"

**Review by tautschnig — APPROVED** [review]

File: src/solvers/smt2/smt2_conv.cpp (hunk 4 above)
Comment (SaswatPadhi) [reply src/solvers/smt2/smt2_conv.cpp]: Thanks, fixed.
