### PR TITLE
Fix unpack_array_vector to produce an array of bytes

### LINKED ISSUE #5718: Invariant violation coming from byte operators
CBMC version: 5.20.1 (but appears to be present in 5.18 as well)
Operating system: macOs 10.15
Exact command line resulting in the issue: `make` on `verification/cbmc/proofs/aws_cryptosdk_priv_unwrap_keys` in branch [CBMC-ISSUE-5718](https://github.com/adpaco-aws/aws-encryption-sdk-c/tree/CBMC-ISSUE-5718)
What behaviour did you expect: No errors.
What happened instead: Received the following invariant violation report.

```
--- begin invariant violation report ---
Invariant check failed
File: /tmp/cbmc-20201210-58015-1j6vaer/src/solvers/lowering/byte_operators.cpp:1252 function: lower_byte_extract
Condition: subtype_bits.has_value() && *subtype_bits == 8
Reason: offset bits are byte aligned
Backtrace:
0   cbmc                                0x000000010a64b6fa _Z15print_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 74
1   cbmc                                0x000000010a64bbeb _Z13get_backtracev + 167
2   cbmc                                0x000000010a6b469c _Z29invariant_violated_structuredI17invariant_failedtJRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEENS1_9enable_ifIXsr3std10is_base_ofIS0_T_EE5valueEvE4typeES9_S9_iS9_DpOT0_ + 44
3   cbmc                                0x000000010a65c369 _Z25invariant_violated_stringRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEES7_iS7_S7_ + 9
4   cbmc                                0x000000010a52df9b _Z18lower_byte_extractRK18byte_extract_exprtRK10namespacet + 9291
5   cbmc                                0x000000010a52de07 _Z18lower_byte_extractRK18byte_extract_exprtRK10namespacet + 8887
6   cbmc                                0x000000010a53705e _Z20lower_byte_operatorsRK5exprtRK10namespacet + 275
7   cbmc                                0x000000010a536fc8 _Z20lower_byte_operatorsRK5exprtRK10namespacet + 125
8   cbmc                                0x000000010a536fc8 _Z20lower_byte_operatorsRK5exprtRK10namespacet + 125
9   cbmc                                0x000000010a4ecae4 _ZN7boolbvt16convert_equalityERK11equal_exprt + 180
10  cbmc                                0x000000010a50812c _ZN12bv_pointerst12convert_restERK5exprt + 940
11  cbmc                                0x000000010a544302 _ZN17prop_conv_solvert12convert_boolERK5exprt + 2548
12  cbmc                                0x000000010a543897 _ZN17prop_conv_solvert7convertERK5exprt + 687
13  cbmc                                0x000000010a54505e _ZN17prop_conv_solvert23add_constraints_to_propERK5exprtb + 992
14  cbmc                                0x000000010a34da87 _ZN22symex_target_equationt19convert_assignmentsER19decision_proceduret + 243
15  cbmc                                0x000000010a34d718 _ZN22symex_target_equationt26convert_without_assertionsER19decision_proceduret + 116
16  cbmc                                0x000000010a34eb85 _ZN22symex_target_equationt7convertER19decision_proceduret + 35
17  cbmc                                0x000000010a23f5e2 _Z29convert_symex_target_equationR22symex_target_equationtR19decision_proceduretR16message_handlert + 125
18  cbmc                                0x000000010a240b36 _Z24prepare_property_deciderRNSt3__113unordered_mapI8dstringt14property_infotNS_4hashIS1_EENS_8equal_toIS1_EENS_9allocatorINS_4pairIKS1_S2_EEEEEER22symex_target_equationtR28goto_symex_property_decidertR19ui_message_handlert + 223
19  cbmc                                0x000000010a246cc8 _ZN25multi_path_symex_checkertclERNSt3__113unordered_mapI8dstringt14property_infotNS0_4hashIS2_EENS0_8equal_toIS2_EENS0_9allocatorINS0_4pairIKS2_S3_EEEEEE + 218
20  cbmc                                0x000000010a23db9b _ZN43all_properties_verifier_with_trace_storagetI25multi_path_symex_checkertEclEv + 55
21  cbmc                                0x000000010a2378f3 _ZN19cbmc_parse_optionst4doitEv + 3647
22  cbmc                                0x000000010a6606ac _ZN19parse_options_baset4mainEv + 136
23  cbmc                                0x000000010a22f5ec main + 44
24  libdyld.dylib                       0x00007fff6fe9ccc9 start + 1


--- end invariant violation report ---

```

### PR DESCRIPTION
**Pull request by tautschnig**
We wrongly created a return type (though not the underlying expression,
which was correct!) as an array of elements of the original subtype,
even though the sole purpose of unpack_array_vector is to turn the
original subtype into a sequence of bytes.

We seemingly neither had a test covering this code nor did we have
additional result verification in place. Both are now rectified: a new
regression test is added, and an invariant is checked right after
returning from unpack_rec (which may invoke unpack_array_vector).

Fixes: #5718

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

### CODE REVIEW

File: src/solvers/lowering/byte_operators.cpp [hunk 1]
```diff
@@ -475,26 +475,17 @@ static exprt unpack_array_vector(
...
-      subtype = to_vector_type(src.type()).subtype();
-    }
-    else
-    {
-      array_vector_size = to_array_type(src.type()).size();
-      subtype = to_array_type(src.type()).subtype();
-    }
+    const exprt array_vector_size = src.type().id() == ID_vector
+                                      ? to_vector_type(src.type()).size()
+                                      : to_array_type(src.type()).size();
```
Comment (hannes-steffenhagen-diffblue) [inline src/solvers/lowering/byte_operators.cpp:480]: Good refactor, but would prefer if this was a separate commit

File: src/solvers/lowering/byte_operators.cpp [hunk 2]
```diff
@@ -475,26 +475,17 @@ static exprt unpack_array_vector(
...
 
     return array_comprehension_exprt{
       std::move(array_comprehension_index),
       std::move(body),
       array_typet{
-        *subtype,
-        mult_exprt{*array_vector_size,
-                   from_integer(el_bytes, array_vector_size->type())}}};
+        bv_typet{8},
```
Comment (hannes-steffenhagen-diffblue) [inline src/solvers/lowering/byte_operators.cpp:486]: Yep, can independently confirm this was the problem here

File: src/solvers/lowering/byte_operators.cpp [hunk 3]
```diff
@@ -1034,6 +1025,9 @@ exprt lower_byte_extract(const byte_extract_exprt &src, const namespacet &ns)
   byte_extract_exprt unpacked(src);
   unpacked.op() = unpack_rec(
     src.op(), little_endian, lower_bound_int_opt, upper_bound_int_opt, ns);
+  CHECK_RETURN(
+    to_bitvector_type(to_type_with_subtype(unpacked.op().type()).subtype())
+      .get_width() == 8);
```
Comment (hannes-steffenhagen-diffblue) [inline src/solvers/lowering/byte_operators.cpp:1030]: Good call, should stop a similar issue cropping up going forward a bit earlier.

That said, I'm a bit worried about all the hard-coded 8s and 7s in this module

File: regression/cbmc-library/memcpy-08/main.c [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+
+int __VERIFIER_nondet_int();
+
+void main()
+{
+  size_t size;
+  __CPROVER_assume(size >= 2);
+  // limit the size to ensure size * sizeof(int) wouldn't overflow, and we don't
+  // reach the maximum object size
+  __CPROVER_assume(size <= 1000);
```
Comment (hannes-steffenhagen-diffblue) [inline regression/cbmc-library/memcpy-08/main.c:12]: Good find, I couldn't figure out what exactly was causing the array comprehension to be emitted here. I had considered just writing a unit test for this particular case instead.

**Review by hannes-steffenhagen-diffblue — APPROVED** [review]

File: src/solvers/lowering/byte_operators.cpp (hunk 3 above)
Comment (tautschnig) [reply src/solvers/lowering/byte_operators.cpp:1030]: Ack, I really should revive #917, which would sort this out.

File: src/solvers/lowering/byte_operators.cpp (hunk 1 above)
Comment (tautschnig) [reply src/solvers/lowering/byte_operators.cpp:480]: Done!
