### PR TITLE
Fix side-effect check on loop invariants

### LINKED ISSUE #5915: False positive from side-effect check in loop contracts
**CBMC version:** `develop`
**Operating system:** Mac OS 10.15

Running `--enforce-all-contracts` raises a false positive on the following file:

```c
int main()
{
  int i, N, *a = malloc(sizeof(int));

  for(i = *a; i < N; ++i)
    __CPROVER_loop_invariant(
      (*a > N) ||
      (*a <= i && i <= N)
    )
  {
    ++i;
  }
}
```

**Exact command line:**

```console
$ goto-cc test.c -o 1.gb
$ goto-instrument --enforce-all-contracts 1.gb 2.gb
--- begin invariant violation report ---
Invariant check failed
File: ../src/goto-programs/goto_convert.cpp:877 function: convert_loop_invariant
Condition: loop invariant is not side-effect free
Reason: no_sideeffects.instructions.empty()
Backtrace:
...
```

**What behaviour did you expect:**
`goto-instrument` shouldn't reject this file. The invariant seems free of side effects -- it only performs basic arithmetic comparisons and read-only heap access.

### PR DESCRIPTION
**Pull request by SaswatPadhi**
Fixes #5915.

Invariant predicates were being _cleaned_ (C -> logic via `clean_expr`) within `convert_loop_invariant` and were rejected if any intermediate goto instructions were introduced during the cleaning process. However, this check is overly conservative -- it ends up rejecting some complex, but pure, Boolean expressions that are compiled to multiple goto instructions.

We replace this logic with a call to `has_subexpr` with `ID_side_effect`.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- N/A ~~The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/~~
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- N/A ~~My commit message includes data points confirming performance improvements (if claimed).~~
- [x] My PR is restricted to a single feature or bugfix.
- N/A ~~White-space or formatting changes outside the feature-related changed lines are in commits of their own.~~

### CODE REVIEW

File: src/goto-programs/goto_convert.cpp [hunk 1]
```diff
@@ -868,13 +868,11 @@ void goto_convertt::convert_loop_invariant(
...
-
-  INVARIANT_WITH_DIAGNOSTICS(
-    no_sideeffects.instructions.empty(),
-    "loop invariant is not side-effect free",
-    code.find_source_location());
+  // Loop contracts are expanded to assertions (and assumptions)
+  // at multiple code points around a loop.
+  // Rather than performing `clean_expr` during compilation,
+  // we convert the invariant to logic at these various code points
+  // only when they are enforced (using goto-instrument).
```
Comment (martin-cs) [inline src/goto-programs/goto_convert.cpp]: So... this means that the output of goto_convert will no longer be side effect free?  So I can now write code that has a different meaning if run with and without code contracts?  That doesn't seem like a very safe design.

Comment (tautschnig) [reply src/goto-programs/goto_convert.cpp]: Without having reviewed the details just yet: the short term idea is to move all invariant-related processing (as far as possible) to `code_contracts.cpp`, knowing that this will leave annotations in there that wouldn't satisfy side-effect freedom. Once this has been cleaned up (right now it's a mess with parts of the processing happening in all sorts of places), it should be fully integrated into goto-program conversion, possibly leaving little or (ideally) nothing left in `goto-instrument`.

**Comment by SaswatPadhi** [comment]
@martin-cs @tautschnig 

After a lot of back and forth discussion and changes, it seemed like at least for the invariants that we currently write, it's sufficient to just check for `ID_side_effect` subexpressions. I left a TODO to revisit the `has_sideeffect` function later and allow calling functions that have an empty ASSIGNS clause from within loop invariants. If you think we might also need to handle some other cases, please suggest -- I'd be happy to include them as part of this change, or leave a TODO to revisit later (if it gets too complicated).

File: src/goto-programs/goto_convert_side_effect.cpp [hunk 2]
```diff
@@ -35,6 +35,24 @@ bool goto_convertt::has_function_call(const exprt &expr)
...
+
+  for(const auto &op : expr.operands())
+  {
+    if(goto_convertt::has_sideeffect(op))
+      return true;
+  }
+
+  return false;
+}
+
```
Comment (tautschnig) [inline src/goto-programs/goto_convert_side_effect.cpp]: Good call out that this was never implemented. That said, can you actually do this a bit different as follows:
1) Get rid of the declaration as well.
2) At the point where you will currently need it, just use `has_subexpr(expr, ID_side_effect);` (from `util/expr_util.h`).

File: src/goto-instrument/code_contracts.cpp [hunk 3]
```diff
@@ -112,17 +112,20 @@ static void check_apply_invariants(
 
   // assert the invariant
   {
-    goto_programt::targett a = havoc_code.add(
-      goto_programt::make_assertion(invariant, loop_head->source_location));
-    a->source_location.set_comment("Check loop invariant before entry");
+    auto assertion = code_assertt(invariant);
+    assertion.add_source_location().swap(loop_head->source_location);
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.cpp]: Is `swap` the right thing to do here?

File: src/goto-instrument/code_contracts.cpp [hunk 4]
```diff
@@ -112,17 +112,20 @@ static void check_apply_invariants(
 
   // assert the invariant
   {
-    goto_programt::targett a = havoc_code.add(
-      goto_programt::make_assertion(invariant, loop_head->source_location));
-    a->source_location.set_comment("Check loop invariant before entry");
+    auto assertion = code_assertt(invariant);
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.cpp]: Nit picking: is this use of `auto` adding value? Wouldn't `code_assertt assertion{invariant};` be even fewer characters and thus less cognitive load?

File: src/goto-instrument/code_contracts.cpp [hunk 5]
```diff
@@ -112,17 +112,20 @@ static void check_apply_invariants(
...
+      "Check loop invariant before entry");
   }
 
   // havoc variables being written to
   build_havoc_code(loop_head, modifies, havoc_code);
 
   // assume the invariant
-  havoc_code.add(
-    goto_programt::make_assumption(invariant, loop_head->source_location));
+  auto assumption = code_assumet(invariant);
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.cpp]: As above: does `auto` add value?

File: src/goto-instrument/code_contracts.cpp [hunk 6]
```diff
@@ -138,11 +141,14 @@ static void check_apply_invariants(
 
   // assert the invariant at the end of the loop body
   {
-    goto_programt::instructiont a =
-      goto_programt::make_assertion(invariant, loop_end->source_location);
-    a.source_location.set_comment("Check that loop invariant is preserved");
-    goto_function.body.insert_before_swap(loop_end, a);
-    ++loop_end;
+    auto assertion = code_assertt(invariant);
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.cpp]: Does `auto` add value?

File: src/goto-instrument/code_contracts.cpp [hunk 7]
```diff
@@ -112,17 +112,20 @@ static void check_apply_invariants(
...
   }
 
   // havoc variables being written to
   build_havoc_code(loop_head, modifies, havoc_code);
 
   // assume the invariant
-  havoc_code.add(
-    goto_programt::make_assumption(invariant, loop_head->source_location));
+  auto assumption = code_assumet(invariant);
+  assumption.add_source_location().swap(loop_head->source_location);
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.cpp]: Given the earlier use of `swap`, there won't be any source location in here?

File: src/goto-instrument/code_contracts.cpp [hunk 8]
```diff
@@ -138,11 +141,14 @@ static void check_apply_invariants(
 
   // assert the invariant at the end of the loop body
   {
-    goto_programt::instructiont a =
-      goto_programt::make_assertion(invariant, loop_end->source_location);
-    a.source_location.set_comment("Check that loop invariant is preserved");
-    goto_function.body.insert_before_swap(loop_end, a);
-    ++loop_end;
+    auto assertion = code_assertt(invariant);
+    assertion.add_source_location().swap(loop_end->source_location);
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.cpp]: As above: nothing left to swap in.

File: src/goto-instrument/code_contracts.h [hunk 9]
```diff
@@ -18,6 +18,8 @@ Date: February 2016
 #include <string>
 #include <unordered_set>
 
+#include <analyses/local_may_alias.h>
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.h]: No need to have this in the header file, a forward declaration will do.

File: src/goto-instrument/code_contracts.h [hunk 10]
```diff
@@ -26,6 +28,8 @@ Date: February 2016
 #include <util/namespace.h>
 #include <util/pointer_expr.h>
 
+#include "loop_utils.h"
```
Comment (tautschnig) [inline src/goto-instrument/code_contracts.h:30]: Wouldn't forward declarations do the trick?

File: src/goto-programs/goto_convert.cpp [hunk 11]
```diff
@@ -868,13 +868,11 @@ void goto_convertt::convert_loop_invariant(
...
     return;
 
-  goto_programt no_sideeffects;
-  clean_expr(invariant, no_sideeffects, mode);
-
-  INVARIANT_WITH_DIAGNOSTICS(
-    no_sideeffects.instructions.empty(),
-    "loop invariant is not side-effect free",
-    code.find_source_location());
+  if(has_sideeffect(invariant))
```
Comment (tautschnig) [inline src/goto-programs/goto_convert.cpp]: See comment in the previous commit: use `has_subexpr(invariant, ID_side_effect)`

**Review by tautschnig — APPROVED** [review]

File: src/goto-instrument/code_contracts.h (hunk 10 above)
Comment (SaswatPadhi) [reply src/goto-instrument/code_contracts.h:30]: Sorry, resolved this comment by mistake without addressing it.

I `#include`d this header file for the `loopt` type, which is `typedef`ed as:

```c
typedef const natural_loops_mutablet::natural_loopt loopt;
```

Could I forward declare it here somehow? I wasn't sure how to.

Comment (tautschnig) [reply src/goto-instrument/code_contracts.h:30]: I believe one of `typename loopt;` or `class loopt;` might still work, and likely the compiler will telly you if it doesn't :-) Not high priority, though.

File: src/goto-programs/goto_convert_class.h [hunk 12]
```diff
@@ -97,7 +97,6 @@ class goto_convertt:public messaget
 
   void rewrite_boolean(exprt &dest);
 
-  static bool has_sideeffect(const exprt &expr);
```
Comment (martin-cs) [inline src/goto-programs/goto_convert_class.h:100]: Why is this removed?

File: src/goto-programs/goto_convert.cpp [hunk 13]
```diff
@@ -868,13 +868,11 @@ void goto_convertt::convert_loop_invariant(
...
     return;
 
-  goto_programt no_sideeffects;
-  clean_expr(invariant, no_sideeffects, mode);
-
-  INVARIANT_WITH_DIAGNOSTICS(
-    no_sideeffects.instructions.empty(),
-    "loop invariant is not side-effect free",
-    code.find_source_location());
+  if(has_subexpr(invariant, ID_side_effect))
```
Comment (martin-cs) [inline src/goto-programs/goto_convert.cpp:871]: As I recall, this was the really contentious part last time around.  This seems much less disruptive.

I think throwing the exception is correct because the user can trigger this even if the tool is non-buggy.  I wonder if it would be more user-friendly to check this earlier but ... I guess we need to check it here as well.

I wonder if this might still be a bit too conservative but, if it works for you then fine.

**Review by martin-cs — APPROVED** [review]
My initial reason for objection, that we were changing a major post condition of goto-convert is gone so there is no reason for me to block this.

Some thoughts:
*. Are similar conditions checked for pre/post?
*. Are the restrictions documented in the manual?

Longer-term, do we want to ban function calls from these annotations?  One thing I found nice about SPARK was being able to define predicates (like `is_initialised` and `is_well_structured`) using Ada functions.  If there isn't a way of doing this you risk a lot of parallel maintenance when altering common invariants.  I guess macros would be one option but these don't work for things like `is_sorted_tree` and having options of how much to expand them.   This is well beyond the scope of this PR but is something worth thinking about IMHO and will touch this code.

File: src/goto-programs/goto_convert_class.h (hunk 12 above)
Comment (SaswatPadhi) [reply src/goto-programs/goto_convert_class.h:100]: It was never defined, so I removed the declaration as well.

Comment (martin-cs) [reply src/goto-programs/goto_convert_class.h:100]: Sounds good.

File: src/goto-programs/goto_convert.cpp (hunk 13 above)
Comment (SaswatPadhi) [reply src/goto-programs/goto_convert.cpp:871]: Thank you, yes earlier I had removed this part entirely and was doing some checking in `goto-instrument` instead. Now this check is performed at `goto-cc` compilation.

> I wonder if this might still be a bit too conservative but, if it works for you then fine.

I completely agree with you. And it's on our roadmap to allow function calls within contracts, if those functions have an empty assigns clause (so no side effects).

**Comment by SaswatPadhi** [comment]
Thank you for taking a look, @martin-cs.

I just wanted to mention that @feliperodri and I are actively working on the issues that you pointed out:

> Are similar conditions checked for pre/post?

Not currently, but we are fix this during our refactoring pass over the code contracts module

> Are the restrictions documented in the manual?

Good call out! Nope, they are not. I would add it to our TODO list for documentation updates.

> Longer-term, do we want to ban function calls from these annotations?

It's on our roadmap to allow function calls within contracts, if those functions have an empty assigns clause (so no side effects).
